import type { Invoice, BillingData } from "@/types/workspace"

export const mockInvoices: Invoice[] = [
  {
    id: "inv-001",
    invoiceNumber: "INV-2025-001",
    date: "2025-01-01",
    dueDate: "2025-01-15",
    amount: 500.0,
    status: "paid",
    description: "Enterprise Plan - Monthly Subscription",
    period: "January 2025",
    pdfUrl: "/invoices/inv-2025-001.pdf",
    receiptUrl: "/receipts/receipt-2025-001.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "January 2025",
    lineItems: [
      {
        id: "li-001-1",
        description: "Enterprise Plan - Monthly Subscription",
        quantity: 1,
        price: 454.55,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 45.45,
        amount: 500.0,
      },
    ],
    subtotal: 454.55,
    tax: 45.45,
    taxRate: "GST on Income (10%)",
  },
  {
    id: "inv-002",
    invoiceNumber: "INV-2025-002",
    date: "2025-02-01",
    dueDate: "2025-02-15",
    amount: 500.0,
    status: "paid",
    description: "Enterprise Plan - Monthly Subscription",
    period: "February 2025",
    pdfUrl: "/invoices/inv-2025-002.pdf",
    receiptUrl: "/receipts/receipt-2025-002.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "February 2025",
    lineItems: [
      {
        id: "li-002-1",
        description: "Enterprise Plan - Monthly Subscription",
        quantity: 1,
        price: 454.55,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 45.45,
        amount: 500.0,
      },
    ],
    subtotal: 454.55,
    tax: 45.45,
    taxRate: "GST on Income (10%)",
  },
  {
    id: "inv-003",
    invoiceNumber: "INV-2025-003",
    date: "2025-03-01",
    dueDate: "2025-03-15",
    amount: 500.0,
    status: "paid",
    description: "Enterprise Plan - Monthly Subscription",
    period: "March 2025",
    pdfUrl: "/invoices/inv-2025-003.pdf",
    receiptUrl: "/receipts/receipt-2025-003.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "March 2025",
    lineItems: [
      {
        id: "li-003-1",
        description: "Enterprise Plan - Monthly Subscription",
        quantity: 1,
        price: 454.55,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 45.45,
        amount: 500.0,
      },
    ],
    subtotal: 454.55,
    tax: 45.45,
    taxRate: "GST on Income (10%)",
  },
  {
    id: "inv-004",
    invoiceNumber: "INV-2025-004",
    date: "2025-04-01",
    dueDate: "2025-04-15",
    amount: 500.0,
    status: "paid",
    description: "Enterprise Plan - Monthly Subscription",
    period: "April 2025",
    pdfUrl: "/invoices/inv-2025-004.pdf",
    receiptUrl: "/receipts/receipt-2025-004.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "April 2025",
    lineItems: [
      {
        id: "li-004-1",
        description: "Enterprise Plan - Monthly Subscription",
        quantity: 1,
        price: 454.55,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 45.45,
        amount: 500.0,
      },
    ],
    subtotal: 454.55,
    tax: 45.45,
    taxRate: "GST on Income (10%)",
  },
  {
    id: "inv-005",
    invoiceNumber: "INV-2025-005",
    date: "2025-05-01",
    dueDate: "2025-05-15",
    amount: 500.0,
    status: "paid",
    description: "Enterprise Plan - Monthly Subscription",
    period: "May 2025",
    pdfUrl: "/invoices/inv-2025-005.pdf",
    receiptUrl: "/receipts/receipt-2025-005.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "May 2025",
    lineItems: [
      {
        id: "li-005-1",
        description: "Enterprise Plan - Monthly Subscription",
        quantity: 1,
        price: 454.55,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 45.45,
        amount: 500.0,
      },
    ],
    subtotal: 454.55,
    tax: 45.45,
    taxRate: "GST on Income (10%)",
  },
  {
    id: "inv-006",
    invoiceNumber: "INV-2025-006",
    date: "2025-06-01",
    dueDate: "2025-06-15",
    amount: 500.0,
    status: "paid",
    description: "Enterprise Plan - Monthly Subscription",
    period: "June 2025",
    pdfUrl: "/invoices/inv-2025-006.pdf",
    receiptUrl: "/receipts/receipt-2025-006.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "June 2025",
    lineItems: [
      {
        id: "li-006-1",
        description: "Enterprise Plan - Monthly Subscription",
        quantity: 1,
        price: 454.55,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 45.45,
        amount: 500.0,
      },
    ],
    subtotal: 454.55,
    tax: 45.45,
    taxRate: "GST on Income (10%)",
  },
  {
    id: "inv-007",
    invoiceNumber: "INV-2025-007",
    date: "2025-07-01",
    dueDate: "2025-07-15",
    amount: 500.0,
    status: "paid",
    description: "Enterprise Plan - Monthly Subscription",
    period: "July 2025",
    pdfUrl: "/invoices/inv-2025-007.pdf",
    receiptUrl: "/receipts/receipt-2025-007.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "July 2025",
    lineItems: [
      {
        id: "li-007-1",
        description: "Enterprise Plan - Monthly Subscription",
        quantity: 1,
        price: 454.55,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 45.45,
        amount: 500.0,
      },
    ],
    subtotal: 454.55,
    tax: 45.45,
    taxRate: "GST on Income (10%)",
  },
  {
    id: "inv-008",
    invoiceNumber: "INV-2025-008",
    date: "2025-08-01",
    dueDate: "2025-08-15",
    amount: 500.0,
    status: "paid",
    description: "Enterprise Plan - Monthly Subscription",
    period: "August 2025",
    pdfUrl: "/invoices/inv-2025-008.pdf",
    receiptUrl: "/receipts/receipt-2025-008.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "August 2025",
    lineItems: [
      {
        id: "li-008-1",
        description: "Enterprise Plan - Monthly Subscription",
        quantity: 1,
        price: 454.55,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 45.45,
        amount: 500.0,
      },
    ],
    subtotal: 454.55,
    tax: 45.45,
    taxRate: "GST on Income (10%)",
  },
  {
    id: "inv-009",
    invoiceNumber: "INV-2025-009",
    date: "2025-09-01",
    dueDate: "2025-09-15",
    amount: 500.0,
    status: "paid",
    description: "Enterprise Plan - Monthly Subscription",
    period: "September 2025",
    pdfUrl: "/invoices/inv-2025-009.pdf",
    receiptUrl: "/receipts/receipt-2025-009.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "September 2025",
    lineItems: [
      {
        id: "li-009-1",
        description: "Enterprise Plan - Monthly Subscription",
        quantity: 1,
        price: 454.55,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 45.45,
        amount: 500.0,
      },
    ],
    subtotal: 454.55,
    tax: 45.45,
    taxRate: "GST on Income (10%)",
  },
  {
    id: "inv-010",
    invoiceNumber: "INV-2025-010",
    date: "2025-10-01",
    dueDate: "2025-10-15",
    amount: 500.0,
    status: "paid",
    description: "Enterprise Plan - Monthly Subscription",
    period: "October 2025",
    pdfUrl: "/invoices/inv-2025-010.pdf",
    receiptUrl: "/receipts/receipt-2025-010.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "October 2025",
    lineItems: [
      {
        id: "li-010-1",
        description: "Enterprise Plan - Monthly Subscription",
        quantity: 1,
        price: 454.55,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 45.45,
        amount: 500.0,
      },
    ],
    subtotal: 454.55,
    tax: 45.45,
    taxRate: "GST on Income (10%)",
  },
  {
    id: "inv-011",
    invoiceNumber: "INV-2025-011",
    date: "2025-11-01",
    dueDate: "2025-11-15",
    amount: 500.0,
    status: "pending",
    description: "Enterprise Plan - Monthly Subscription",
    period: "November 2025",
    pdfUrl: "/invoices/inv-2025-011.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "November 2025",
    lineItems: [
      {
        id: "li-011-1",
        description: "Enterprise Plan - Monthly Subscription",
        quantity: 1,
        price: 454.55,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 45.45,
        amount: 500.0,
      },
    ],
    subtotal: 454.55,
    tax: 45.45,
    taxRate: "GST on Income (10%)",
  },
  {
    id: "inv-012",
    invoiceNumber: "INV-2025-012",
    date: "2025-10-15",
    dueDate: "2025-10-20",
    amount: 8857.93,
    status: "overdue",
    description: "Remote Team as a Service",
    period: "October and November 2025",
    pdfUrl: "/invoices/inv-2025-012.pdf",
    contact: {
      name: "Stark Industries Inc.",
      accountNumber: "TMFSTARK12345",
      address: "Penthouse Level, Avengers Tower, Midtown Manhattan, New York City, USA",
    },
    reference: "November 2025",
    lineItems: [
      {
        id: "li-012-1",
        description:
          "Senior Administrator - Natasha Romanoff\nStarted 20/10/2025 and Billed in Advance for October and November",
        quantity: 1.3871,
        price: 2779.13,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 385.49,
        amount: 3854.93,
      },
      {
        id: "li-012-2",
        description:
          "Senior Accountant - Cliff Barton\nStarting 27/10/2025 and Billed in Advance for October and November",
        quantity: 1.1613,
        price: 3614.69,
        discount: 0,
        account: "200 - Sales",
        taxRate: "GST on Income",
        taxAmount: 419.77,
        amount: 4197.74,
      },
    ],
    subtotal: 8052.67,
    tax: 805.26,
    taxRate: "GST on Income (10%)",
  },
]

export const mockBillingData: BillingData = {
  invoices: mockInvoices,
  totalOverdue: mockInvoices.filter((inv) => inv.status === "overdue").reduce((sum, inv) => sum + inv.amount, 0),
  totalPaidThisYear: mockInvoices.filter((inv) => inv.status === "paid").reduce((sum, inv) => sum + inv.amount, 0),
  nextPaymentDue: mockInvoices.find((inv) => inv.status === "pending"),
}
