import type { JobListing } from "@/types/workspace"

export const mockJobListings: JobListing[] = [
  // APPLIED JOBS (applied: true)
  {
    id: "1",
    title: "Senior Full-Stack Developer",
    company: "Teamified",
    companyWebsite: "https://teamified.com",
    location: "Manila, Philippines",
    type: "Full-time",
    salary: "$45k - $65k",
    posted: "2 days ago",
    description: "We're looking for an experienced full-stack developer to join our growing team in Manila.",
    requirements: ["5+ years experience", "React & Node.js", "TypeScript", "AWS"],
    applied: true,
    saved: true,
    invited: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/teamified-logo-100x100-NwpwYu9vSkuPkpVvtw9Esz8i2xD0Q4.png",
    status: "open",
    skillMatch: 88,
    jobSummary:
      "• Lead the development of scalable web applications using modern technologies\n• Collaborate with product and design teams to deliver exceptional user experiences\n• Mentor junior developers and contribute to technical decision-making\n• Optimize application performance and ensure code quality through best practices\n• Participate in agile ceremonies and contribute to sprint planning",
    aboutClient:
      "Teamified is a leading HR technology company that helps businesses build and manage high-performing teams through innovative software solutions.",
    qualifications: [
      "5+ years of professional software development experience",
      "Strong proficiency in React, Node.js, and TypeScript",
      "Experience with AWS cloud services and infrastructure",
      "Solid understanding of RESTful APIs and microservices architecture",
      "Experience with SQL and NoSQL databases",
      "Strong problem-solving and communication skills",
    ],
    responsibilities: [
      "Design and develop scalable full-stack applications",
      "Collaborate with cross-functional teams to define and implement new features",
      "Write clean, maintainable, and well-documented code",
      "Participate in code reviews and provide constructive feedback",
      "Mentor junior developers and contribute to team knowledge sharing",
      "Optimize application performance and ensure high availability",
    ],
    benefits: [
      "Competitive salary and performance bonuses",
      "Health insurance coverage",
      "Flexible work arrangements",
      "Professional development budget",
      "Annual team retreats",
      "Modern office equipment",
    ],
    department: "Engineering",
    reportingTo: "Engineering Manager",
    teamSize: "8-10 engineers",
    workArrangement: "Hybrid (3 days office, 2 days remote)",
    applicationDeadline: "March 15, 2025",
    hiringManager: "Sarah Chen",
    openings: 2,
  },
  {
    id: "2",
    title: "AI Engineer",
    company: "Archa",
    companyWebsite: "https://archa.io",
    location: "Bangalore, India",
    type: "Full-time",
    salary: "$35k - $55k",
    posted: "1 week ago",
    description: "Join our AI team to build cutting-edge machine learning solutions.",
    requirements: ["Python", "TensorFlow/PyTorch", "ML algorithms", "3+ years experience"],
    applied: true,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/archa%20logo-8NVeEWIzgR0Y8aHBeqraSQWXy0mM3f.png",
    status: "open",
    skillMatch: 75,
    applicationStage: "applied",
    takeHomeChallengeCompleted: false,
    aiInterviewCompleted: false,
    finalReviewCompleted: false,
    jobSummary:
      "• Design and implement machine learning models for production systems\n• Work with large datasets to train and optimize AI algorithms\n• Collaborate with engineering teams to integrate ML solutions into products\n• Research and evaluate new AI technologies and methodologies\n• Monitor model performance and implement improvements",
    aboutClient:
      "Archa is a fast-growing AI startup focused on developing next-generation machine learning platforms for enterprises.",
    benefits: [
      "Competitive compensation with equity options",
      "Comprehensive health and wellness benefits",
      "Flexible remote work policy",
      "Learning and development stipend",
      "Conference attendance opportunities",
      "Cutting-edge hardware and tools",
    ],
  },
  {
    id: "3",
    title: "Product Manager",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Sydney, Australia",
    type: "Full-time",
    salary: "$90k - $120k",
    posted: "3 days ago",
    description: "Lead product strategy and execution for our flagship product in Sydney.",
    requirements: ["5+ years PM experience", "Agile/Scrum", "Data-driven", "B2B SaaS"],
    applied: true,
    saved: true,
    invited: true,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    skillMatch: 82,
    jobSummary:
      "• Define and execute product roadmap aligned with business objectives\n• Conduct market research and competitive analysis to identify opportunities\n• Work closely with engineering, design, and sales teams to deliver features\n• Analyze product metrics and user feedback to drive continuous improvement\n• Present product vision and strategy to stakeholders and leadership",
    aboutClient:
      "Volaro Group is a leading B2B SaaS company providing enterprise solutions to businesses worldwide, with a strong presence across Australia, New Zealand, and Southeast Asia.",
    benefits: [
      "Excellent salary package with performance bonuses",
      "Premium health insurance for you and family",
      "Generous parental leave policy",
      "Stock options and equity participation",
      "Professional development and training",
      "Modern Sydney office with amenities",
    ],
  },
  {
    id: "4",
    title: "DevOps Engineer",
    company: "Zai",
    companyWebsite: "https://zai.com",
    location: "Colombo, Sri Lanka",
    type: "Full-time",
    salary: "$30k - $45k",
    posted: "5 days ago",
    description: "Build and maintain our cloud infrastructure and CI/CD pipelines.",
    requirements: ["Kubernetes", "Docker", "AWS/GCP", "Terraform", "4+ years experience"],
    applied: true,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-mmp2tJXTgvXPeoADutH4SeeUExx52Q.png",
    status: "open",
    skillMatch: 70,
    jobSummary:
      "• Design and maintain scalable cloud infrastructure on AWS/GCP\n• Implement and optimize CI/CD pipelines for automated deployments\n• Monitor system performance and ensure high availability\n• Automate infrastructure provisioning using Infrastructure as Code\n• Collaborate with development teams to improve deployment processes",
    aboutClient:
      "Zai is a rapidly growing software company specializing in cloud-native solutions and infrastructure management.",
    benefits: [
      "Competitive salary with annual increments",
      "Health and life insurance coverage",
      "Work from home flexibility",
      "Annual performance bonuses",
      "Professional development opportunities",
      "Collaborative team environment",
    ],
  },
  {
    id: "5",
    title: "Senior Backend Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Melbourne, Australia",
    type: "Full-time",
    salary: "$95k - $125k",
    posted: "1 week ago",
    description: "Build scalable backend systems for our enterprise platform.",
    requirements: ["Node.js", "PostgreSQL", "Microservices", "6+ years experience"],
    applied: true,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    skillMatch: 85,
    jobSummary:
      "• Design and implement scalable backend services and APIs\n• Optimize database performance and query efficiency\n• Collaborate with frontend teams to deliver seamless integrations\n• Implement security best practices and data protection measures\n• Participate in system architecture decisions",
    aboutClient:
      "Volaro Group is a leading B2B SaaS company providing enterprise solutions to businesses worldwide, with a strong presence across Australia, New Zealand, and Southeast Asia.",
  },

  // INVITED JOBS (invited: true, applied: false)
  {
    id: "6",
    title: "UX/UI Designer",
    company: "Teamified",
    companyWebsite: "https://teamified.com",
    location: "Remote",
    type: "Full-time",
    salary: "$50k - $70k",
    posted: "1 day ago",
    description: "Create beautiful and intuitive user experiences for our HR platform.",
    requirements: ["Figma", "User Research", "Prototyping", "4+ years experience"],
    applied: false,
    invited: true,
    saved: true,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/teamified-logo-100x100-NwpwYu9vSkuPkpVvtw9Esz8i2xD0Q4.png",
    status: "open",
    skillMatch: 90,
    benefits: [
      "Competitive salary with performance bonuses",
      "Fully remote work environment",
      "Health and wellness benefits",
      "Professional development and design conference budget",
      "Latest design tools and software licenses",
      "Flexible working hours",
    ],
  },
  {
    id: "7",
    title: "Machine Learning Engineer",
    company: "Archa",
    companyWebsite: "https://archa.io",
    location: "Singapore",
    type: "Full-time",
    salary: "$70k - $95k",
    posted: "2 days ago",
    description: "Develop and deploy ML models for our AI platform.",
    requirements: ["Python", "TensorFlow", "MLOps", "5+ years experience"],
    applied: false,
    invited: true,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/archa%20logo-8NVeEWIzgR0Y8aHBeqraSQWXy0mM3f.png",
    status: "open",
    skillMatch: 87,
    benefits: [
      "Excellent compensation with equity options",
      "Premium health insurance coverage",
      "Visa sponsorship and relocation assistance",
      "Access to cutting-edge AI research and tools",
      "Conference and research publication support",
      "Collaborative innovation culture",
    ],
  },
  {
    id: "8",
    title: "Senior Frontend Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Auckland, New Zealand",
    type: "Full-time",
    salary: "$85k - $110k",
    posted: "3 days ago",
    description: "Build next-generation web experiences with React and TypeScript.",
    requirements: ["React", "TypeScript", "CSS-in-JS", "6+ years experience"],
    applied: false,
    invited: true,
    saved: true,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    skillMatch: 92,
    benefits: [
      "Competitive salary with annual bonuses",
      "Comprehensive health and dental insurance",
      "Generous parental leave policy",
      "Stock options and equity participation",
      "Professional development opportunities",
      "Modern Auckland office with amenities",
    ],
  },
  {
    id: "9",
    title: "Cloud Solutions Architect",
    company: "Zai",
    companyWebsite: "https://zai.com",
    location: "Dubai, UAE",
    type: "Full-time",
    salary: "$95k - $130k",
    posted: "1 week ago",
    description: "Design and implement enterprise-scale cloud architectures.",
    requirements: ["AWS/Azure", "Microservices", "Security", "7+ years experience"],
    applied: false,
    invited: true,
    saved: true,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-mmp2tJXTgvXPeoADutH4SeeUExx52Q.png",
    status: "open",
    skillMatch: 88,
    benefits: [
      "Tax-free salary in Dubai",
      "Housing and transportation allowance",
      "Premium health insurance for family",
      "Annual flight tickets home",
      "Professional certifications and training",
      "International work environment",
    ],
  },
  {
    id: "10",
    title: "Data Scientist",
    company: "Archa",
    companyWebsite: "https://archa.io",
    location: "London, UK",
    type: "Full-time",
    salary: "$80k - $110k",
    posted: "4 days ago",
    description: "Analyze data and build predictive models to drive AI insights.",
    requirements: ["Python", "SQL", "Statistics", "5+ years experience"],
    applied: false,
    invited: true,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/archa%20logo-8NVeEWIzgR0Y8aHBeqraSQWXy0mM3f.png",
    status: "open",
    skillMatch: 83,
    benefits: [
      "Competitive UK salary with bonuses",
      "Private healthcare and pension scheme",
      "Visa sponsorship available",
      "Flexible hybrid work arrangement",
      "Learning and development budget",
      "Central London office location",
    ],
  },
  {
    id: "11",
    title: "Security Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Singapore",
    type: "Full-time",
    salary: "$90k - $120k",
    posted: "5 days ago",
    description: "Protect our infrastructure and applications from security threats.",
    requirements: ["Penetration Testing", "Security Audits", "OWASP", "5+ years experience"],
    applied: false,
    invited: true,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    skillMatch: 79,
    benefits: [
      "Excellent compensation package",
      "Comprehensive health and wellness benefits",
      "Security certification sponsorship",
      "Work permit and relocation support",
      "Annual performance bonuses",
      "Vibrant Singapore tech hub location",
    ],
  },

  // SAVED JOBS (saved: true, applied: false, invited: false)
  {
    id: "12",
    title: "Mobile Developer (iOS)",
    company: "Teamified",
    companyWebsite: "https://teamified.com",
    location: "Manila, Philippines",
    type: "Full-time",
    salary: "$40k - $60k",
    posted: "1 week ago",
    description: "Develop cutting-edge iOS applications for our HR platform.",
    requirements: ["Swift", "SwiftUI", "iOS SDK", "4+ years experience"],
    applied: false,
    invited: false,
    saved: true,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/teamified-logo-100x100-NwpwYu9vSkuPkpVvtw9Esz8i2xD0Q4.png",
    status: "open",
    skillMatch: 81,
    benefits: [
      "Competitive salary with annual increases",
      "Health insurance coverage",
      "Flexible work arrangements",
      "Apple hardware and development tools",
      "Professional development opportunities",
      "Team building and social events",
    ],
  },
  {
    id: "13",
    title: "QA Automation Engineer",
    company: "Zai",
    companyWebsite: "https://zai.com",
    location: "Kuala Lumpur, Malaysia",
    type: "Full-time",
    salary: "$35k - $50k",
    posted: "3 days ago",
    description: "Build and maintain automated testing frameworks for web applications.",
    requirements: ["Selenium", "Cypress", "Jest", "CI/CD", "4+ years experience"],
    applied: false,
    invited: false,
    saved: true,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-mmp2tJXTgvXPeoADutH4SeeUExx52Q.png",
    status: "open",
    skillMatch: 76,
    benefits: [
      "Competitive salary package",
      "Medical and dental insurance",
      "Work from home flexibility",
      "Annual performance bonuses",
      "Training and certification support",
      "Modern KL office with amenities",
    ],
  },
  {
    id: "14",
    title: "Technical Writer",
    company: "Archa",
    companyWebsite: "https://archa.io",
    location: "Remote",
    type: "Full-time",
    salary: "$45k - $65k",
    posted: "5 days ago",
    description: "Create comprehensive technical documentation for our AI platform.",
    requirements: ["Technical Writing", "API Documentation", "Markdown", "3+ years experience"],
    applied: false,
    invited: false,
    saved: true,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/archa%20logo-8NVeEWIzgR0Y8aHBeqraSQWXy0mM3f.png",
    status: "open",
    skillMatch: 72,
    benefits: [
      "Fully remote position",
      "Flexible working hours",
      "Health and wellness stipend",
      "Professional writing tools and software",
      "Learning and development budget",
      "Collaborative global team",
    ],
  },
  {
    id: "15",
    title: "Platform Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Brisbane, Australia",
    type: "Full-time",
    salary: "$85k - $115k",
    posted: "2 days ago",
    description: "Build internal developer platforms and tooling.",
    requirements: ["Kubernetes", "GitOps", "Platform Engineering", "4+ years experience"],
    applied: false,
    invited: false,
    saved: true,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    skillMatch: 80,
    benefits: [
      "Excellent salary with performance bonuses",
      "Premium health insurance",
      "Generous parental leave",
      "Stock options available",
      "Professional development support",
      "Brisbane office with great facilities",
    ],
  },

  // BROWSE JOBS (applied: false, invited: false, saved: false) - At least 20 jobs
  {
    id: "16",
    title: "Site Reliability Engineer",
    company: "Zai",
    companyWebsite: "https://zai.com",
    location: "Bangkok, Thailand",
    type: "Full-time",
    salary: "$50k - $70k",
    posted: "1 day ago",
    description: "Ensure high availability and performance of production systems.",
    requirements: ["Kubernetes", "Monitoring", "Incident Response", "5+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-mmp2tJXTgvXPeoADutH4SeeUExx52Q.png",
    status: "open",
    skillMatch: 84,
    benefits: [
      "Competitive salary package",
      "Health and life insurance",
      "Flexible work arrangements",
      "Annual performance bonuses",
      "Professional certifications support",
      "Bangkok city center office",
    ],
  },
  {
    id: "17",
    title: "Business Analyst",
    company: "Teamified",
    companyWebsite: "https://teamified.com",
    location: "Cebu, Philippines",
    type: "Full-time",
    salary: "$35k - $50k",
    posted: "6 days ago",
    description: "Transform business requirements into technical specifications.",
    requirements: ["Business Analysis", "SQL", "Agile", "3+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/teamified-logo-100x100-NwpwYu9vSkuPkpVvtw9Esz8i2xD0Q4.png",
    status: "open",
    skillMatch: 68,
    benefits: [
      "Competitive compensation",
      "Health insurance coverage",
      "Work from home options",
      "Professional development opportunities",
      "Team activities and events",
      "Career growth pathways",
    ],
  },
  {
    id: "18",
    title: "Solutions Architect",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Perth, Australia",
    type: "Full-time",
    salary: "$105k - $140k",
    posted: "2 weeks ago",
    description: "Design technical solutions for enterprise clients.",
    requirements: ["System Design", "Cloud Platforms", "Client Facing", "6+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    skillMatch: 82,
    benefits: [
      "Excellent salary with bonuses",
      "Comprehensive health benefits",
      "Stock options and equity",
      "Professional certifications sponsored",
      "Client engagement opportunities",
      "Perth office with modern facilities",
    ],
  },
  {
    id: "19",
    title: "Data Engineer",
    company: "Archa",
    companyWebsite: "https://archa.io",
    location: "Mumbai, India",
    type: "Full-time",
    salary: "$40k - $60k",
    posted: "4 days ago",
    description: "Build and maintain large-scale data pipelines for AI systems.",
    requirements: ["Spark", "Airflow", "SQL", "Python", "4+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/archa%20logo-8NVeEWIzgR0Y8aHBeqraSQWXy0mM3f.png",
    status: "open",
    skillMatch: 78,
    benefits: [
      "Competitive salary with equity",
      "Health insurance for family",
      "Flexible hybrid work model",
      "Learning and development budget",
      "Access to AI tools and platforms",
      "Vibrant Mumbai tech community",
    ],
  },
  {
    id: "20",
    title: "Network Engineer",
    company: "Zai",
    companyWebsite: "https://zai.com",
    location: "Hong Kong",
    type: "Full-time",
    salary: "$65k - $85k",
    posted: "1 week ago",
    description: "Design and maintain enterprise network infrastructure.",
    requirements: ["Cisco", "Network Security", "BGP/OSPF", "5+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-mmp2tJXTgvXPeoADutH4SeeUExx52Q.png",
    status: "open",
    skillMatch: 71,
    benefits: [
      "Competitive Hong Kong salary",
      "Medical and dental coverage",
      "Annual performance bonuses",
      "Cisco certification support",
      "Professional development opportunities",
      "Central Hong Kong office location",
    ],
  },
  {
    id: "21",
    title: "Computer Vision Engineer",
    company: "Archa",
    companyWebsite: "https://archa.io",
    location: "Hyderabad, India",
    type: "Full-time",
    salary: "$45k - $65k",
    posted: "3 days ago",
    description: "Develop computer vision algorithms for AI applications.",
    requirements: ["OpenCV", "Deep Learning", "Python", "4+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/archa%20logo-8NVeEWIzgR0Y8aHBeqraSQWXy0mM3f.png",
    status: "open",
    skillMatch: 75,
    benefits: [
      "Competitive compensation with equity",
      "Comprehensive health insurance",
      "Flexible work arrangements",
      "Research and conference support",
      "Access to GPU clusters and tools",
      "Collaborative AI research environment",
    ],
  },
  {
    id: "22",
    title: "Scrum Master",
    company: "Teamified",
    companyWebsite: "https://teamified.com",
    location: "Remote",
    type: "Full-time",
    salary: "$50k - $70k",
    posted: "1 week ago",
    description: "Facilitate agile processes and remove blockers for development teams.",
    requirements: ["Scrum Certification", "Agile Coaching", "JIRA", "4+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/teamified-logo-100x100-NwpwYu9vSkuPkpVvtw9Esz8i2xD0Q4.png",
    status: "open",
    skillMatch: 65,
    benefits: [
      "Fully remote position",
      "Flexible working hours",
      "Health and wellness benefits",
      "Agile certification support",
      "Professional coaching opportunities",
      "Global team collaboration",
    ],
  },
  {
    id: "23",
    title: "Full-Stack Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Wellington, New Zealand",
    type: "Full-time",
    salary: "$75k - $100k",
    posted: "3 days ago",
    description: "Build web applications using modern JavaScript frameworks.",
    requirements: ["React", "Node.js", "PostgreSQL", "4+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    skillMatch: 79,
    benefits: [
      "Competitive salary with bonuses",
      "Health and dental insurance",
      "Generous leave policies",
      "Stock options available",
      "Professional development budget",
      "Wellington office with great culture",
    ],
  },
  {
    id: "24",
    title: "MLOps Engineer",
    company: "Archa",
    companyWebsite: "https://archa.io",
    location: "Pune, India",
    type: "Full-time",
    salary: "$40k - $60k",
    posted: "5 days ago",
    description: "Deploy and monitor machine learning models in production.",
    requirements: ["MLflow", "Kubeflow", "Python", "Docker", "3+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/archa%20logo-8NVeEWIzgR0Y8aHBeqraSQWXy0mM3f.png",
    status: "open",
    skillMatch: 77,
    benefits: [
      "Competitive salary with equity options",
      "Health insurance coverage",
      "Flexible hybrid work model",
      "Learning and development support",
      "Access to ML infrastructure and tools",
      "Pune tech hub location",
    ],
  },
  {
    id: "25",
    title: "Technical Support Engineer",
    company: "Zai",
    companyWebsite: "https://zai.com",
    location: "Remote",
    type: "Full-time",
    salary: "$30k - $45k",
    posted: "1 week ago",
    description: "Provide technical support and troubleshooting for enterprise customers.",
    requirements: ["Customer Support", "Debugging", "Documentation", "2+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-mmp2tJXTgvXPeoADutH4SeeUExx52Q.png",
    status: "open",
    skillMatch: 62,
    benefits: [
      "Fully remote work",
      "Flexible schedule",
      "Health insurance",
      "Professional development opportunities",
      "Career progression pathways",
      "Supportive team environment",
    ],
  },
  {
    id: "26",
    title: "Engineering Manager",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Sydney, Australia",
    type: "Full-time",
    salary: "$130k - $170k",
    posted: "2 days ago",
    description: "Lead and mentor a team of software engineers to deliver high-quality products.",
    requirements: ["Team Leadership", "Technical Background", "Agile", "7+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    skillMatch: 86,
    benefits: [
      "Executive compensation package",
      "Premium health benefits for family",
      "Generous parental leave",
      "Significant stock options and equity",
      "Leadership development programs",
      "Sydney CBD office with premium amenities",
    ],
  },
  {
    id: "27",
    title: "Growth Engineer",
    company: "Teamified",
    companyWebsite: "https://teamified.com",
    location: "Davao, Philippines",
    type: "Full-time",
    salary: "$40k - $60k",
    posted: "4 days ago",
    description: "Drive user acquisition and retention through data-driven experiments.",
    requirements: ["A/B Testing", "Analytics", "Full-Stack", "4+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/teamified-logo-100x100-NwpwYu9vSkuPkpVvtw9Esz8i2xD0Q4.png",
    status: "open",
    skillMatch: 73,
    benefits: [
      "Competitive salary with performance bonuses",
      "Health insurance coverage",
      "Flexible work arrangements",
      "Analytics tools and resources",
      "Professional development opportunities",
      "Dynamic startup environment",
    ],
  },
  {
    id: "28",
    title: "Backend Developer",
    company: "Zai",
    companyWebsite: "https://zai.com",
    location: "Jakarta, Indonesia",
    type: "Full-time",
    salary: "$35k - $50k",
    posted: "6 days ago",
    description: "Build scalable backend systems for cloud-native applications.",
    requirements: ["Node.js", "PostgreSQL", "Redis", "4+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-mmp2tJXTgvXPeoADutH4SeeUExx52Q.png",
    status: "open",
    skillMatch: 74,
    benefits: [
      "Competitive salary package",
      "Health and life insurance",
      "Work from home flexibility",
      "Annual performance bonuses",
      "Professional development support",
      "Jakarta office with modern facilities",
    ],
  },
  {
    id: "29",
    title: "AI Research Scientist",
    company: "Archa",
    companyWebsite: "https://archa.io",
    location: "Chennai, India",
    type: "Full-time",
    salary: "$50k - $75k",
    posted: "1 week ago",
    description: "Conduct research on cutting-edge AI and machine learning techniques.",
    requirements: ["PhD/Masters", "Research Experience", "Deep Learning", "Publications"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/archa%20logo-8NVeEWIzgR0Y8aHBeqraSQWXy0mM3f.png",
    status: "open",
    skillMatch: 70,
    benefits: [
      "Competitive research salary with equity",
      "Comprehensive health insurance",
      "Research publication support",
      "Conference attendance and travel",
      "Access to state-of-the-art AI infrastructure",
      "Collaborative research environment",
    ],
  },
  {
    id: "30",
    title: "Product Designer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Melbourne, Australia",
    type: "Full-time",
    salary: "$80k - $105k",
    posted: "3 days ago",
    description: "Design intuitive product experiences for enterprise software.",
    requirements: ["Figma", "Design Systems", "User Research", "5+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    skillMatch: 81,
    benefits: [
      "Excellent salary with bonuses",
      "Premium health and dental insurance",
      "Generous parental leave",
      "Stock options available",
      "Design conference and workshop budget",
      "Melbourne office with creative spaces",
    ],
  },
  {
    id: "31",
    title: "Customer Success Manager",
    company: "Teamified",
    companyWebsite: "https://teamified.com",
    location: "Remote",
    type: "Full-time",
    salary: "$45k - $65k",
    posted: "5 days ago",
    description: "Ensure customer satisfaction and drive product adoption.",
    requirements: ["Customer Success", "SaaS Experience", "Communication", "3+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/teamified-logo-100x100-NwpwYu9vSkuPkpVvtw9Esz8i2xD0Q4.png",
    status: "open",
    skillMatch: 66,
    benefits: [
      "Fully remote position",
      "Flexible working hours",
      "Health and wellness benefits",
      "Customer success tools and training",
      "Career growth opportunities",
      "Collaborative team culture",
    ],
  },
  {
    id: "32",
    title: "Infrastructure Engineer",
    company: "Zai",
    companyWebsite: "https://zai.com",
    location: "Manila, Philippines",
    type: "Full-time",
    salary: "$40k - $60k",
    posted: "1 week ago",
    description: "Manage and optimize cloud infrastructure for high-scale applications.",
    requirements: ["AWS/GCP", "Terraform", "Monitoring", "5+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-mmp2tJXTgvXPeoADutH4SeeUExx52Q.png",
    status: "open",
    skillMatch: 76,
    benefits: [
      "Competitive salary with annual increases",
      "Health and life insurance",
      "Flexible work arrangements",
      "Cloud certification support",
      "Professional development opportunities",
      "Modern Manila office",
    ],
  },
  {
    id: "33",
    title: "Sales Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Singapore",
    type: "Full-time",
    salary: "$85k - $115k",
    posted: "2 days ago",
    description: "Bridge technical solutions with customer needs in enterprise sales.",
    requirements: ["Technical Background", "Sales Experience", "Presentations", "4+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    skillMatch: 69,
    benefits: [
      "Base salary plus commission structure",
      "Comprehensive health benefits",
      "Work permit sponsorship",
      "Sales training and development",
      "Travel opportunities",
      "Singapore office with great location",
    ],
  },
  {
    id: "34",
    title: "NLP Engineer",
    company: "Archa",
    companyWebsite: "https://archa.io",
    location: "Bangalore, India",
    type: "Full-time",
    salary: "$45k - $70k",
    posted: "4 days ago",
    description: "Build natural language processing models for AI applications.",
    requirements: ["NLP", "Transformers", "Python", "4+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/archa%20logo-8NVeEWIzgR0Y8aHBeqraSQWXy0mM3f.png",
    status: "open",
    skillMatch: 80,
    benefits: [
      "Competitive salary with equity options",
      "Comprehensive health insurance",
      "Flexible hybrid work model",
      "NLP research and conference support",
      "Access to GPU clusters and LLM tools",
      "Bangalore AI community access",
    ],
  },
  {
    id: "35",
    title: "HR Technology Specialist",
    company: "Teamified",
    companyWebsite: "https://teamified.com",
    location: "Manila, Philippines",
    type: "Full-time",
    salary: "$40k - $55k",
    posted: "1 week ago",
    description: "Implement and optimize HR technology solutions for clients.",
    requirements: ["HRIS Systems", "Implementation", "Training", "3+ years experience"],
    applied: false,
    invited: false,
    saved: false,
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/teamified-logo-100x100-NwpwYu9vSkuPkpVvtw9Esz8i2xD0Q4.png",
    status: "open",
    skillMatch: 67,
    benefits: [
      "Competitive salary package",
      "Health insurance coverage",
      "Flexible work arrangements",
      "HR technology training and certifications",
      "Client engagement opportunities",
      "Career development pathways",
    ],
  },
]
