import type { JobListing, CandidateProfile } from "@/types/workspace"
import { mockCandidates } from "./mock-candidates"

// Extended JobListing interface to include matchedCandidates
export interface HiringManagerJob extends JobListing {
  matchedCandidates?: CandidateProfile[]
}

// Helper function to get random candidates with varied skill matches
function getRandomCandidates(count: number, baseSkillMatch = 85): CandidateProfile[] {
  const shuffled = [...mockCandidates].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count).map((candidate, index) => ({
    ...candidate,
    skillMatch: baseSkillMatch - index * 2, // Decreasing skill match
  }))
}

export const mockHiringManagerJobs: HiringManagerJob[] = [
  // 1 DRAFT JOB
  {
    id: "hm-job-1",
    title: "Senior Backend Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Singapore",
    type: "Full-time",
    salary: "SGD 120,000 - 160,000",
    posted: "Draft",
    description:
      "We're looking for a Senior Backend Engineer to join our growing team and help build scalable microservices architecture.",
    requirements: [
      "5+ years of backend development experience",
      "Strong proficiency in Node.js and TypeScript",
      "Experience with microservices architecture",
      "Knowledge of AWS or similar cloud platforms",
    ],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "draft",
    responsibilities: [
      "Design and implement scalable backend services",
      "Collaborate with frontend teams on API design",
      "Optimize database queries and system performance",
      "Mentor junior developers",
    ],
    qualifications: [
      "Bachelor's degree in Computer Science or related field",
      "Experience with PostgreSQL and Redis",
      "Strong understanding of RESTful APIs and GraphQL",
      "Excellent problem-solving skills",
    ],
    benefits: [
      "Competitive salary and equity",
      "Flexible work arrangements",
      "Health insurance",
      "Professional development budget",
    ],
    matchedCandidates: [], // Draft job has no matched candidates yet
  },

  // 3 OPEN JOBS
  {
    id: "hm-job-2",
    title: "Frontend Developer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Manila, Philippines",
    type: "Full-time",
    salary: "PHP 800,000 - 1,200,000",
    posted: "2 days ago",
    description:
      "Join our AI-powered platform team to build beautiful, responsive user interfaces that delight our customers.",
    requirements: [
      "3+ years of React development experience",
      "Strong CSS and responsive design skills",
      "Experience with TypeScript",
      "Familiarity with modern build tools",
    ],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    responsibilities: [
      "Build reusable React components",
      "Implement pixel-perfect designs",
      "Optimize frontend performance",
      "Collaborate with designers and backend engineers",
    ],
    qualifications: [
      "Strong portfolio of web applications",
      "Experience with Next.js and TailwindCSS",
      "Understanding of web accessibility standards",
      "Good communication skills",
    ],
    benefits: ["Competitive salary", "Remote work options", "Health and dental insurance", "Annual learning budget"],
    matchedCandidates: [], // 0 matched candidates
  },
  {
    id: "hm-job-3",
    title: "Full-Stack Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Kuala Lumpur, Malaysia",
    type: "Full-time",
    salary: "MYR 100,000 - 140,000",
    posted: "1 week ago",
    description:
      "We're seeking a talented Full-Stack Engineer to help us build enterprise B2B SaaS solutions for our global clients.",
    requirements: [
      "4+ years of full-stack development experience",
      "Proficiency in React and Node.js",
      "Experience with SQL and NoSQL databases",
      "Strong problem-solving skills",
    ],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    responsibilities: [
      "Develop full-stack features from design to deployment",
      "Write clean, maintainable code",
      "Participate in code reviews",
      "Contribute to technical architecture decisions",
    ],
    qualifications: [
      "Bachelor's degree in Computer Science or equivalent",
      "Experience with AWS or Azure",
      "Knowledge of CI/CD pipelines",
      "Team player with good communication skills",
    ],
    benefits: [
      "Competitive salary and bonuses",
      "Flexible working hours",
      "Comprehensive health coverage",
      "Career growth opportunities",
    ],
    matchedCandidates: getRandomCandidates(3, 92), // 3 matched candidates
  },
  {
    id: "hm-job-4",
    title: "Senior Software Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Singapore",
    type: "Full-time",
    salary: "SGD 130,000 - 180,000",
    posted: "3 days ago",
    description:
      "Join our cloud-native software team to build cutting-edge payment solutions that power businesses across Asia-Pacific.",
    requirements: [
      "6+ years of software engineering experience",
      "Strong expertise in distributed systems",
      "Experience with Kubernetes and Docker",
      "Excellent coding and design skills",
    ],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "open",
    responsibilities: [
      "Design and build scalable payment systems",
      "Lead technical initiatives and mentor team members",
      "Ensure high availability and performance",
      "Collaborate with product and design teams",
    ],
    qualifications: [
      "Bachelor's or Master's degree in Computer Science",
      "Deep understanding of system design and architecture",
      "Experience with high-traffic production systems",
      "Strong leadership and communication skills",
    ],
    benefits: [
      "Competitive salary and equity package",
      "Flexible work arrangements",
      "Premium health insurance",
      "Professional development opportunities",
      "Annual company retreats",
    ],
    matchedCandidates: getRandomCandidates(20, 95), // 20 matched candidates
  },

  // 10 CLOSED JOBS
  {
    id: "hm-job-5",
    title: "DevOps Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Remote - Asia",
    type: "Full-time",
    salary: "USD 80,000 - 120,000",
    posted: "Closed 2 weeks ago",
    description: "Managed our cloud infrastructure and CI/CD pipelines. Position filled.",
    requirements: ["5+ years DevOps experience", "AWS expertise", "Kubernetes knowledge"],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "closed",
    matchedCandidates: getRandomCandidates(8, 88),
  },
  {
    id: "hm-job-6",
    title: "Product Designer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Manila, Philippines",
    type: "Full-time",
    salary: "PHP 900,000 - 1,400,000",
    posted: "Closed 1 month ago",
    description: "Designed user experiences for our AI platform. Position filled.",
    requirements: ["4+ years product design experience", "Figma expertise", "Portfolio required"],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "closed",
    matchedCandidates: getRandomCandidates(5, 85),
  },
  {
    id: "hm-job-7",
    title: "Data Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Singapore",
    type: "Full-time",
    salary: "SGD 110,000 - 150,000",
    posted: "Closed 3 weeks ago",
    description: "Built data pipelines and analytics infrastructure. Position filled.",
    requirements: ["5+ years data engineering", "Python and SQL", "Big data experience"],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "closed",
    matchedCandidates: getRandomCandidates(12, 90),
  },
  {
    id: "hm-job-8",
    title: "Mobile Developer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Kuala Lumpur, Malaysia",
    type: "Full-time",
    salary: "MYR 110,000 - 150,000",
    posted: "Closed 2 months ago",
    description: "Developed mobile payment applications. Position filled.",
    requirements: ["4+ years mobile development", "React Native or Flutter", "iOS and Android"],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "closed",
    matchedCandidates: getRandomCandidates(15, 87),
  },
  {
    id: "hm-job-9",
    title: "QA Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Manila, Philippines",
    type: "Full-time",
    salary: "PHP 700,000 - 1,000,000",
    posted: "Closed 1 month ago",
    description: "Ensured quality through automated testing. Position filled.",
    requirements: ["3+ years QA experience", "Test automation", "Selenium or Cypress"],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "closed",
    matchedCandidates: getRandomCandidates(6, 82),
  },
  {
    id: "hm-job-10",
    title: "Security Engineer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Singapore",
    type: "Full-time",
    salary: "SGD 120,000 - 170,000",
    posted: "Closed 6 weeks ago",
    description: "Secured our infrastructure and applications. Position filled.",
    requirements: ["5+ years security experience", "Penetration testing", "Security certifications"],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "closed",
    matchedCandidates: getRandomCandidates(4, 91),
  },
  {
    id: "hm-job-11",
    title: "Technical Writer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Remote - Asia",
    type: "Full-time",
    salary: "USD 60,000 - 90,000",
    posted: "Closed 2 months ago",
    description: "Created technical documentation and guides. Position filled.",
    requirements: ["3+ years technical writing", "API documentation", "Strong English skills"],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "closed",
    matchedCandidates: getRandomCandidates(7, 80),
  },
  {
    id: "hm-job-12",
    title: "Engineering Manager",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Singapore",
    type: "Full-time",
    salary: "SGD 150,000 - 200,000",
    posted: "Closed 3 months ago",
    description: "Led engineering team and drove technical strategy. Position filled.",
    requirements: ["8+ years engineering", "3+ years management", "Strong leadership"],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "closed",
    matchedCandidates: getRandomCandidates(10, 93),
  },
  {
    id: "hm-job-13",
    title: "Backend Developer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Kuala Lumpur, Malaysia",
    type: "Full-time",
    salary: "MYR 90,000 - 130,000",
    posted: "Closed 1 month ago",
    description: "Built RESTful APIs and microservices. Position filled.",
    requirements: ["3+ years backend development", "Node.js or Python", "Database design"],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "closed",
    matchedCandidates: getRandomCandidates(9, 86),
  },
  {
    id: "hm-job-14",
    title: "UI/UX Designer",
    company: "Volaro Group",
    companyWebsite: "https://volaro.com",
    location: "Manila, Philippines",
    type: "Full-time",
    salary: "PHP 800,000 - 1,200,000",
    posted: "Closed 5 weeks ago",
    description: "Designed intuitive user interfaces. Position filled.",
    requirements: ["4+ years UI/UX design", "Figma and Sketch", "User research experience"],
    logo: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/volaro_group_logo-2prnJRSB6Fg6rRS6ksnWN8hBwzIJFJ.jpeg",
    status: "closed",
    matchedCandidates: getRandomCandidates(11, 84),
  },
]
