import type { CandidateProfile } from "@/types/workspace"

export const mockCandidates: CandidateProfile[] = [
  {
    id: "cand-1",
    name: "Sarah Chen",
    avatar: "SC",
    title: "Senior Full-Stack Developer",
    location: "Manila, Philippines",
    experience: "6 years",
    email: "sarah.chen@email.com",
    phone: "+63 917 123 4567",
    linkedin: "https://linkedin.com/in/sarahchen",
    github: "https://github.com/sarahchen",
    portfolio: "https://sarahchen.dev",
    summary:
      "Passionate full-stack developer with 6 years of experience building scalable web applications. Specialized in React, Node.js, and cloud architecture. Led multiple teams to deliver high-impact projects on time and under budget. Strong advocate for clean code and test-driven development.",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "AWS",
      "PostgreSQL",
      "Docker",
      "Kubernetes",
      "GraphQL",
      "Next.js",
      "TailwindCSS",
    ],
    skillMatch: 95,
    resumeUrl: "https://example.com/resume/sarah-chen.pdf",
    takeHomeChallengeStatus: "completed",
    takeHomeChallengeScore: 92,
    takeHomeChallengeSubmission: "https://github.com/sarahchen/coding-challenge",
    takeHomeChallengeNotes:
      "Excellent code quality with comprehensive tests. Implemented all required features plus bonus optimizations. Clean architecture and well-documented code.",
    aiInterviewStatus: "completed",
    aiInterviewScore: 88,
    aiInterviewRecordingUrl: "https://example.com/interviews/sarah-chen.mp4",
    aiInterviewTranscript:
      "Q: Tell me about your experience with microservices.\nA: I've architected and deployed multiple microservices systems using Node.js and Docker. In my last role, I led the migration from a monolith to microservices, which improved our deployment frequency by 300%...",
    aiGeneratedInsights: [
      "Strong technical skills with proven track record in full-stack development",
      "Excellent problem-solving abilities demonstrated in coding challenge",
      "Great communication skills and team leadership experience",
      "Proactive learner who stays current with latest technologies",
      "Cultural fit: Values collaboration and continuous improvement",
    ],
  },
  {
    id: "cand-2",
    name: "Michael Rodriguez",
    avatar: "MR",
    title: "Full-Stack Engineer",
    location: "Cebu, Philippines",
    experience: "4 years",
    email: "michael.r@email.com",
    phone: "+63 918 234 5678",
    github: "https://github.com/mrodriguez",
    summary:
      "Creative full-stack engineer with a passion for building user-centric applications. Experience with modern JavaScript frameworks and cloud technologies. Strong focus on performance optimization and accessibility.",
    skills: ["React", "Node.js", "TypeScript", "MongoDB", "AWS", "Redux", "Express", "Jest", "Git"],
    skillMatch: 87,
    resumeUrl: "https://example.com/resume/michael-rodriguez.pdf",
    takeHomeChallengeStatus: "completed",
    takeHomeChallengeScore: 85,
    takeHomeChallengeSubmission: "https://github.com/mrodriguez/challenge-solution",
    takeHomeChallengeNotes:
      "Good implementation with solid fundamentals. Code is clean and functional. Could improve on edge case handling and test coverage.",
    aiInterviewStatus: "completed",
    aiInterviewScore: 82,
    aiInterviewRecordingUrl: "https://example.com/interviews/michael-rodriguez.mp4",
    aiInterviewTranscript:
      "Q: How do you approach performance optimization?\nA: I start by profiling the application to identify bottlenecks. Then I focus on the areas with the biggest impact, like code splitting, lazy loading, and optimizing database queries...",
    aiGeneratedInsights: [
      "Solid technical foundation with room for growth",
      "Good understanding of modern web development practices",
      "Enthusiastic and eager to learn new technologies",
      "Would benefit from mentorship in system design",
      "Strong potential for growth within the team",
    ],
  },
  {
    id: "cand-3",
    name: "Priya Sharma",
    avatar: "PS",
    title: "Software Engineer",
    location: "Bangalore, India",
    experience: "5 years",
    email: "priya.sharma@email.com",
    linkedin: "https://linkedin.com/in/priyasharma",
    github: "https://github.com/priyasharma",
    summary:
      "Detail-oriented software engineer with expertise in building scalable backend systems. Strong background in distributed systems and database optimization. Passionate about writing efficient, maintainable code.",
    skills: ["Node.js", "Python", "AWS", "PostgreSQL", "Redis", "Docker", "Microservices", "REST APIs", "GraphQL"],
    skillMatch: 82,
    resumeUrl: "https://example.com/resume/priya-sharma.pdf",
    takeHomeChallengeStatus: "completed",
    takeHomeChallengeScore: 78,
    takeHomeChallengeSubmission: "https://github.com/priyasharma/take-home",
    takeHomeChallengeNotes:
      "Functional solution that meets requirements. Backend implementation is strong, but frontend could use improvement. Good database design.",
    aiInterviewStatus: "completed",
    aiInterviewScore: 80,
    aiInterviewRecordingUrl: "https://example.com/interviews/priya-sharma.mp4",
    aiInterviewTranscript:
      "Q: Describe your experience with distributed systems.\nA: I've worked extensively with microservices architectures, implementing event-driven systems using message queues and ensuring data consistency across services...",
    aiGeneratedInsights: [
      "Strong backend development skills",
      "Good understanding of system architecture and scalability",
      "Frontend skills could be strengthened",
      "Excellent problem-solving approach",
      "Would thrive in a backend-focused role",
    ],
  },
  {
    id: "cand-4",
    name: "James Wilson",
    avatar: "JW",
    title: "Frontend Developer",
    location: "Sydney, Australia",
    experience: "3 years",
    email: "james.wilson@email.com",
    phone: "+61 412 345 678",
    portfolio: "https://jameswilson.design",
    summary:
      "Creative frontend developer with an eye for design and user experience. Specialized in React and modern CSS. Passionate about creating accessible and performant web applications.",
    skills: ["React", "TypeScript", "CSS", "TailwindCSS", "Next.js", "Figma", "Accessibility", "Performance"],
    skillMatch: 75,
    resumeUrl: "https://example.com/resume/james-wilson.pdf",
    takeHomeChallengeStatus: "pending",
    aiInterviewStatus: "completed",
    aiInterviewScore: 75,
    aiInterviewRecordingUrl: "https://example.com/interviews/james-wilson.mp4",
    aiInterviewTranscript:
      "Q: How do you ensure accessibility in your applications?\nA: I follow WCAG guidelines, use semantic HTML, ensure proper keyboard navigation, and test with screen readers. Accessibility is a core part of my development process...",
    aiGeneratedInsights: [
      "Strong frontend skills with focus on UX",
      "Good understanding of accessibility best practices",
      "Limited backend experience",
      "Great attention to detail in UI implementation",
      "Would excel in a frontend-focused role",
    ],
  },
  {
    id: "cand-5",
    name: "Elena Popescu",
    avatar: "EP",
    title: "Full-Stack Developer",
    location: "Remote (Europe)",
    experience: "7 years",
    email: "elena.popescu@email.com",
    linkedin: "https://linkedin.com/in/elenapopescu",
    github: "https://github.com/elenapopescu",
    summary:
      "Experienced full-stack developer with a strong background in e-commerce and fintech. Expert in building secure, scalable applications. Proven track record of delivering complex projects.",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "PostgreSQL",
      "AWS",
      "Security",
      "Payment Integration",
      "CI/CD",
      "Terraform",
    ],
    skillMatch: 91,
    resumeUrl: "https://example.com/resume/elena-popescu.pdf",
    takeHomeChallengeStatus: "completed",
    takeHomeChallengeScore: 90,
    takeHomeChallengeSubmission: "https://github.com/elenapopescu/challenge",
    takeHomeChallengeNotes:
      "Outstanding submission with production-ready code. Implemented security best practices and comprehensive error handling. Excellent documentation.",
    aiInterviewStatus: "completed",
    aiInterviewScore: 89,
    aiInterviewRecordingUrl: "https://example.com/interviews/elena-popescu.mp4",
    aiInterviewTranscript:
      "Q: Tell me about your experience with payment systems.\nA: I've integrated multiple payment gateways including Stripe, PayPal, and local payment methods. Security is paramount, so I always follow PCI compliance guidelines...",
    aiGeneratedInsights: [
      "Highly experienced with proven expertise in full-stack development",
      "Strong focus on security and best practices",
      "Excellent technical communication skills",
      "Self-motivated and works well independently",
      "Would be a strong senior addition to the team",
    ],
  },
]
