import type { CandidateProfile } from "@/types/workspace"

export const mockCandidates: CandidateProfile[] = [
  {
    id: "cand-1",
    name: "Sarah Chen",
    avatar: "/professional-headshot-asian-woman-software-develop.jpg",
    title: "Senior Full-Stack Developer",
    location: "Manila, Philippines",
    experience: "6 years",
    email: "sarah.chen@email.com",
    phone: "+63 917 123 4567",
    linkedin: "https://linkedin.com/in/sarahchen",
    github: "https://github.com/sarahchen",
    portfolio: "https://sarahchen.dev",
    summary:
      "Passionate full-stack developer with 6 years of experience building scalable web applications. Specialized in React, Node.js, and cloud architecture. Led multiple teams to deliver high-impact projects on time and under budget. Strong advocate for clean code and test-driven development.",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "AWS",
      "PostgreSQL",
      "Docker",
      "Kubernetes",
      "GraphQL",
      "Next.js",
      "TailwindCSS",
    ],
    skillMatch: 95,
    resumeUrl: "https://example.com/resume/sarah-chen.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/sarahchen/ecommerce-platform",
    submissionFiles: [
      { name: "project-documentation.pdf", url: "#", type: "application/pdf", size: "2.4 MB" },
      { name: "architecture-diagram.png", url: "#", type: "image/png", size: "856 KB" },
      { name: "test-coverage-report.html", url: "#", type: "text/html", size: "124 KB" },
    ],
    submissionLinks: ["https://demo.sarahchen-challenge.vercel.app", "https://www.loom.com/share/demo-walkthrough"],
    takeHomeChallengeNotes:
      "Excellent code quality with comprehensive tests. Implemented all required features plus bonus optimizations. Clean architecture and well-documented code.",
    codeReviewPoints: [
      "Excellent component architecture with clear separation of concerns",
      "Comprehensive test coverage (95%) including unit, integration, and e2e tests",
      "Implemented all required features plus performance optimizations",
      "Clean, readable code with consistent naming conventions",
      "Proper error handling and edge case management",
      "Well-documented API endpoints with OpenAPI/Swagger specs",
      "Efficient database queries with proper indexing",
      "Security best practices: input validation, SQL injection prevention, XSS protection",
      "Responsive design that works seamlessly across all devices",
      "Bonus: Added caching layer that improved response times by 40%",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/sarah-chen.mp4",
    aiInterviewTranscript:
      "Q: Tell me about your experience with microservices.\nA: I've architected and deployed multiple microservices systems using Node.js and Docker. In my last role, I led the migration from a monolith to microservices, which improved our deployment frequency by 300%...",
    aiGeneratedInsights: [
      "Strong technical skills with proven track record in full-stack development",
      "Excellent problem-solving abilities demonstrated in coding challenge",
      "Great communication skills and team leadership experience",
      "Proactive learner who stays current with latest technologies",
      "Cultural fit: Values collaboration and continuous improvement",
    ],
  },
  {
    id: "cand-2",
    name: "Michael Rodriguez",
    avatar: "/professional-headshot-hispanic-man-software-engine.jpg",
    title: "Full-Stack Engineer",
    location: "Quezon City, Philippines",
    experience: "4 years",
    email: "michael.rodriguez@email.com",
    phone: "+63 917 234 5678",
    linkedin: "https://linkedin.com/in/michaelrodriguez",
    github: "https://github.com/mrodriguez",
    summary:
      "Enthusiastic full-stack engineer with a strong foundation in modern web technologies. Experienced in building responsive applications with React and Node.js. Quick learner with a passion for solving complex problems and delivering user-friendly solutions.",
    skills: ["React", "Node.js", "JavaScript", "MongoDB", "Express", "REST APIs", "Git", "Agile", "CSS", "HTML"],
    skillMatch: 87,
    resumeUrl: "https://example.com/resume/michael-rodriguez.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/mrodriguez/task-manager-app",
    submissionFiles: [
      { name: "README.md", url: "#", type: "text/markdown", size: "12 KB" },
      { name: "setup-instructions.pdf", url: "#", type: "application/pdf", size: "456 KB" },
    ],
    submissionLinks: ["https://task-manager-demo.netlify.app"],
    takeHomeChallengeNotes: "Good implementation with solid fundamentals. Code is clean and functional.",
    codeReviewPoints: [
      "Solid implementation of core features with good code organization",
      "Functional components with proper React hooks usage",
      "Good test coverage (75%) for critical paths",
      "RESTful API design follows standard conventions",
      "Basic error handling implemented for common scenarios",
      "Responsive layout works well on mobile and desktop",
      "Code is readable with helpful comments where needed",
      "Could improve: More comprehensive input validation",
      "Could improve: Additional edge case handling in async operations",
      "Overall: Strong fundamentals with room for optimization",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/michael-rodriguez.mp4",
    aiGeneratedInsights: [
      "Solid technical foundation with good understanding of web development",
      "Eager to learn and grow in the role",
      "Good communication skills and positive attitude",
      "Shows potential for rapid skill development",
    ],
  },
  {
    id: "cand-3",
    name: "Priya Sharma",
    avatar: "/professional-headshot-indian-woman-software-engine.jpg",
    title: "Software Engineer",
    location: "Makati, Philippines",
    experience: "5 years",
    email: "priya.sharma@email.com",
    phone: "+63 917 345 6789",
    linkedin: "https://linkedin.com/in/priyasharma",
    github: "https://github.com/psharma",
    summary:
      "Detail-oriented software engineer with expertise in backend development and database optimization. Strong problem-solving skills and experience with distributed systems. Committed to writing efficient, maintainable code.",
    skills: ["Python", "Django", "PostgreSQL", "Redis", "Docker", "AWS", "REST APIs", "GraphQL", "React", "TypeScript"],
    skillMatch: 82,
    resumeUrl: "https://example.com/resume/priya-sharma.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/psharma/api-service",
    submissionFiles: [
      { name: "api-documentation.pdf", url: "#", type: "application/pdf", size: "1.8 MB" },
      { name: "postman-collection.json", url: "#", type: "application/json", size: "45 KB" },
    ],
    submissionLinks: ["https://api-demo.psharma.dev/docs"],
    takeHomeChallengeNotes: "Strong backend implementation with excellent database design.",
    codeReviewPoints: [
      "Excellent database schema design with proper normalization",
      "Efficient API endpoints with good performance characteristics",
      "Comprehensive error handling and logging",
      "Good test coverage for backend logic (82%)",
      "Well-structured code with clear separation of concerns",
      "Proper use of caching strategies for frequently accessed data",
      "Security: Implemented authentication and authorization correctly",
      "Could improve: Frontend UI could be more polished",
      "Could improve: Additional client-side validation",
      "Overall: Strong backend skills, frontend needs development",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/priya-sharma.mp4",
    aiGeneratedInsights: [
      "Exceptional backend development skills",
      "Strong understanding of system architecture and scalability",
      "Methodical approach to problem-solving",
      "Would benefit from more frontend experience",
    ],
  },
  {
    id: "cand-4",
    name: "James Wilson",
    avatar: "/professional-headshot-caucasian-man-frontend-devel.jpg",
    title: "Frontend Developer",
    location: "Taguig, Philippines",
    experience: "3 years",
    email: "james.wilson@email.com",
    phone: "+63 917 456 7890",
    linkedin: "https://linkedin.com/in/jameswilson",
    github: "https://github.com/jwilson",
    portfolio: "https://jameswilson.design",
    summary:
      "Creative frontend developer with a keen eye for design and user experience. Specialized in building beautiful, accessible interfaces with React and modern CSS. Passionate about creating delightful user experiences.",
    skills: [
      "React",
      "TypeScript",
      "CSS",
      "TailwindCSS",
      "Figma",
      "Next.js",
      "Framer Motion",
      "Accessibility",
      "UI/UX",
    ],
    skillMatch: 75,
    resumeUrl: "https://example.com/resume/james-wilson.pdf",
    takeHomeChallengeStatus: "completed",
    submissionFiles: [
      { name: "design-mockups.fig", url: "#", type: "application/figma", size: "3.2 MB" },
      { name: "component-library.pdf", url: "#", type: "application/pdf", size: "1.1 MB" },
    ],
    submissionLinks: ["https://jwilson-challenge.vercel.app", "https://www.figma.com/file/design-system"],
    takeHomeChallengeNotes: "Beautiful UI with excellent attention to detail and accessibility.",
    codeReviewPoints: [
      "Outstanding UI/UX design with pixel-perfect implementation",
      "Excellent accessibility features (WCAG 2.1 AA compliant)",
      "Smooth animations and transitions using Framer Motion",
      "Responsive design that adapts beautifully to all screen sizes",
      "Clean, maintainable CSS with good use of Tailwind utilities",
      "Well-structured React components with proper prop types",
      "Good attention to performance (lazy loading, code splitting)",
      "Could improve: Backend integration could be more robust",
      "Could improve: More comprehensive error handling",
      "Overall: Exceptional frontend skills, needs backend development",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/james-wilson.mp4",
    aiGeneratedInsights: [
      "Exceptional design and frontend development skills",
      "Strong focus on user experience and accessibility",
      "Creative problem solver with attention to detail",
      "Would benefit from more backend experience",
    ],
  },
  {
    id: "cand-5",
    name: "Elena Popescu",
    avatar: "/professional-headshot-european-woman-developer-exp.jpg",
    title: "Full-Stack Developer",
    location: "Pasig, Philippines",
    experience: "7 years",
    email: "elena.popescu@email.com",
    phone: "+63 917 567 8901",
    linkedin: "https://linkedin.com/in/elenapopescu",
    github: "https://github.com/epopescu",
    summary:
      "Experienced full-stack developer with a strong background in e-commerce and fintech applications. Expert in building secure, scalable systems with modern technologies. Proven track record of delivering complex projects.",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "PostgreSQL",
      "Redis",
      "AWS",
      "Stripe",
      "Security",
      "Microservices",
      "Docker",
    ],
    skillMatch: 91,
    resumeUrl: "https://example.com/resume/elena-popescu.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/epopescu/payment-system",
    submissionFiles: [
      { name: "technical-writeup.pdf", url: "#", type: "application/pdf", size: "2.1 MB" },
      { name: "security-audit.pdf", url: "#", type: "application/pdf", size: "890 KB" },
      { name: "performance-metrics.xlsx", url: "#", type: "application/vnd.ms-excel", size: "234 KB" },
    ],
    submissionLinks: ["https://payment-demo.epopescu.dev", "https://docs.epopescu.dev/api-reference"],
    takeHomeChallengeNotes: "Exceptional work with strong focus on security and scalability.",
    codeReviewPoints: [
      "Excellent system architecture with microservices design",
      "Comprehensive security implementation (encryption, authentication, authorization)",
      "High test coverage (92%) with thorough integration tests",
      "Efficient database design with proper indexing and query optimization",
      "Well-documented code and API endpoints",
      "Proper error handling and logging throughout the application",
      "Performance optimizations: caching, lazy loading, code splitting",
      "Scalable infrastructure setup with Docker and AWS",
      "Clean code with consistent patterns and best practices",
      "Bonus: Implemented CI/CD pipeline with automated testing and deployment",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/elena-popescu.mp4",
    aiGeneratedInsights: [
      "Highly experienced with strong technical leadership",
      "Excellent understanding of security and scalability",
      "Proven track record in complex system development",
      "Strong communication and documentation skills",
      "Great cultural fit with focus on quality and best practices",
    ],
  },
  {
    id: "cand-6",
    name: "David Kim",
    avatar: "/professional-asian-man-developer.jpg",
    title: "DevOps Engineer",
    location: "Cebu City, Philippines",
    experience: "5 years",
    email: "david.kim@email.com",
    phone: "+63 917 678 9012",
    linkedin: "https://linkedin.com/in/davidkim",
    github: "https://github.com/dkim",
    summary:
      "DevOps engineer specializing in cloud infrastructure and CI/CD automation. Experienced with AWS, Kubernetes, and Terraform. Passionate about improving deployment processes and system reliability.",
    skills: ["AWS", "Kubernetes", "Docker", "Terraform", "Jenkins", "Python", "Bash", "Monitoring", "CI/CD", "Linux"],
    skillMatch: 88,
    resumeUrl: "https://example.com/resume/david-kim.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/dkim/infrastructure-automation",
    submissionFiles: [
      { name: "infrastructure-diagram.pdf", url: "#", type: "application/pdf", size: "1.5 MB" },
      { name: "deployment-guide.md", url: "#", type: "text/markdown", size: "34 KB" },
    ],
    submissionLinks: ["https://monitoring-dashboard.dkim.dev"],
    takeHomeChallengeNotes: "Excellent infrastructure setup with comprehensive monitoring and automation.",
    codeReviewPoints: [
      "Well-architected cloud infrastructure with high availability",
      "Comprehensive CI/CD pipeline with automated testing and deployment",
      "Excellent monitoring and alerting setup",
      "Infrastructure as code with Terraform best practices",
      "Good security practices with proper IAM roles and policies",
      "Efficient container orchestration with Kubernetes",
      "Clear documentation for deployment and maintenance",
      "Cost optimization strategies implemented",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/david-kim.mp4",
    aiGeneratedInsights: [
      "Strong DevOps and infrastructure expertise",
      "Excellent problem-solving for system reliability",
      "Good communication about technical concepts",
      "Proactive approach to automation and optimization",
    ],
  },
  {
    id: "cand-7",
    name: "Maria Santos",
    avatar: "/professional-filipina-woman-developer.jpg",
    title: "Mobile Developer",
    location: "Manila, Philippines",
    experience: "4 years",
    email: "maria.santos@email.com",
    phone: "+63 917 789 0123",
    linkedin: "https://linkedin.com/in/mariasantos",
    github: "https://github.com/msantos",
    portfolio: "https://mariasantos.dev",
    summary:
      "Mobile developer with expertise in React Native and native iOS development. Experienced in building cross-platform applications with excellent performance and user experience. Strong focus on mobile UI/UX best practices.",
    skills: [
      "React Native",
      "Swift",
      "iOS",
      "Android",
      "TypeScript",
      "Redux",
      "Firebase",
      "Mobile UI/UX",
      "App Store",
      "Push Notifications",
    ],
    skillMatch: 84,
    resumeUrl: "https://example.com/resume/maria-santos.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/msantos/mobile-app",
    submissionFiles: [
      { name: "app-demo-video.mp4", url: "#", type: "video/mp4", size: "15.2 MB" },
      { name: "design-specs.pdf", url: "#", type: "application/pdf", size: "2.3 MB" },
    ],
    submissionLinks: ["https://apps.apple.com/app/demo", "https://play.google.com/store/apps/demo"],
    takeHomeChallengeNotes: "Excellent mobile app with smooth performance and intuitive UI.",
    codeReviewPoints: [
      "Well-structured React Native codebase with clean architecture",
      "Smooth animations and transitions",
      "Excellent mobile UI/UX following platform guidelines",
      "Good performance optimization for mobile devices",
      "Proper state management with Redux",
      "Offline functionality implemented correctly",
      "Good test coverage for critical features",
      "Could improve: More comprehensive error handling",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/maria-santos.mp4",
    aiGeneratedInsights: [
      "Strong mobile development skills across platforms",
      "Excellent understanding of mobile UI/UX patterns",
      "Good attention to performance and user experience",
      "Enthusiastic about mobile technology trends",
    ],
  },
  {
    id: "cand-8",
    name: "Ahmed Hassan",
    avatar: "/professional-middle-eastern-man-developer.jpg",
    title: "Backend Engineer",
    location: "Davao City, Philippines",
    experience: "6 years",
    email: "ahmed.hassan@email.com",
    phone: "+63 917 890 1234",
    linkedin: "https://linkedin.com/in/ahmedhassan",
    github: "https://github.com/ahassan",
    summary:
      "Backend engineer with deep expertise in distributed systems and microservices architecture. Specialized in building high-performance APIs and scalable backend infrastructure. Strong focus on system design and optimization.",
    skills: [
      "Java",
      "Spring Boot",
      "Microservices",
      "Kafka",
      "PostgreSQL",
      "Redis",
      "Docker",
      "Kubernetes",
      "AWS",
      "System Design",
    ],
    skillMatch: 93,
    resumeUrl: "https://example.com/resume/ahmed-hassan.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/ahassan/microservices-platform",
    submissionFiles: [
      { name: "system-architecture.pdf", url: "#", type: "application/pdf", size: "3.1 MB" },
      { name: "api-documentation.pdf", url: "#", type: "application/pdf", size: "1.8 MB" },
      { name: "load-test-results.pdf", url: "#", type: "application/pdf", size: "945 KB" },
    ],
    submissionLinks: ["https://api.ahassan.dev/docs", "https://monitoring.ahassan.dev"],
    takeHomeChallengeNotes: "Outstanding backend architecture with excellent scalability and performance.",
    codeReviewPoints: [
      "Excellent microservices architecture with proper service boundaries",
      "High-performance API design with efficient data handling",
      "Comprehensive error handling and resilience patterns",
      "Excellent test coverage including integration and load tests",
      "Well-implemented event-driven architecture with Kafka",
      "Proper database design with optimization for high throughput",
      "Good monitoring and observability setup",
      "Security best practices throughout the codebase",
      "Clean code with SOLID principles",
      "Bonus: Implemented circuit breaker and retry patterns",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/ahmed-hassan.mp4",
    aiGeneratedInsights: [
      "Exceptional backend and system design skills",
      "Deep understanding of distributed systems",
      "Strong problem-solving for scalability challenges",
      "Excellent technical communication",
      "Great fit for senior backend role",
    ],
  },
  {
    id: "cand-9",
    name: "Lisa Anderson",
    avatar: "/professional-caucasian-woman-developer.jpg",
    title: "Frontend Engineer",
    location: "Bonifacio Global City, Philippines",
    experience: "3 years",
    email: "lisa.anderson@email.com",
    phone: "+63 917 901 2345",
    linkedin: "https://linkedin.com/in/lisaanderson",
    github: "https://github.com/landerson",
    portfolio: "https://lisaanderson.design",
    summary:
      "Frontend engineer passionate about creating beautiful, performant web applications. Specialized in React, TypeScript, and modern CSS. Strong focus on accessibility and responsive design.",
    skills: [
      "React",
      "TypeScript",
      "Next.js",
      "TailwindCSS",
      "CSS",
      "HTML",
      "Accessibility",
      "Performance",
      "Figma",
      "Storybook",
    ],
    skillMatch: 79,
    resumeUrl: "https://example.com/resume/lisa-anderson.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/landerson/portfolio-site",
    submissionFiles: [
      { name: "design-system.pdf", url: "#", type: "application/pdf", size: "2.7 MB" },
      { name: "accessibility-report.pdf", url: "#", type: "application/pdf", size: "678 KB" },
    ],
    submissionLinks: ["https://demo.lisaanderson.dev", "https://storybook.lisaanderson.dev"],
    takeHomeChallengeNotes: "Beautiful frontend implementation with excellent attention to accessibility.",
    codeReviewPoints: [
      "Excellent UI implementation with pixel-perfect design",
      "Strong accessibility features (WCAG 2.1 AA compliant)",
      "Good performance optimization techniques",
      "Clean, maintainable component architecture",
      "Responsive design that works across all devices",
      "Good use of TypeScript for type safety",
      "Well-documented components with Storybook",
      "Could improve: More comprehensive testing",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/lisa-anderson.mp4",
    aiGeneratedInsights: [
      "Strong frontend development skills",
      "Excellent eye for design and user experience",
      "Good understanding of accessibility standards",
      "Eager to learn and improve testing skills",
    ],
  },
  {
    id: "cand-10",
    name: "Carlos Mendoza",
    avatar: "/professional-latino-man-developer.jpg",
    title: "Full-Stack Developer",
    location: "Quezon City, Philippines",
    experience: "5 years",
    email: "carlos.mendoza@email.com",
    phone: "+63 917 012 3456",
    linkedin: "https://linkedin.com/in/carlosmendoza",
    github: "https://github.com/cmendoza",
    summary:
      "Versatile full-stack developer with experience across the entire web development stack. Skilled in building modern web applications with React, Node.js, and cloud technologies. Strong problem-solver with excellent communication skills.",
    skills: ["React", "Node.js", "TypeScript", "MongoDB", "Express", "Next.js", "AWS", "GraphQL", "Jest", "Git"],
    skillMatch: 86,
    resumeUrl: "https://example.com/resume/carlos-mendoza.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/cmendoza/fullstack-app",
    submissionFiles: [
      { name: "project-overview.pdf", url: "#", type: "application/pdf", size: "1.4 MB" },
      { name: "test-results.html", url: "#", type: "text/html", size: "156 KB" },
    ],
    submissionLinks: ["https://demo.cmendoza.dev", "https://api.cmendoza.dev/graphql"],
    takeHomeChallengeNotes: "Solid full-stack implementation with good balance of frontend and backend skills.",
    codeReviewPoints: [
      "Well-balanced full-stack implementation",
      "Clean React components with proper hooks usage",
      "Solid backend API with GraphQL",
      "Good test coverage (78%) across frontend and backend",
      "Proper error handling and validation",
      "Responsive UI with good user experience",
      "Clear code structure and organization",
      "Could improve: More advanced optimization techniques",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/carlos-mendoza.mp4",
    aiGeneratedInsights: [
      "Strong full-stack capabilities",
      "Good balance of frontend and backend skills",
      "Excellent communication and teamwork",
      "Adaptable and quick learner",
    ],
  },
  {
    id: "cand-11",
    name: "Yuki Tanaka",
    avatar: "/professional-japanese-woman-developer.jpg",
    title: "Senior Software Engineer",
    location: "Makati, Philippines",
    experience: "8 years",
    email: "yuki.tanaka@email.com",
    phone: "+63 917 123 4567",
    linkedin: "https://linkedin.com/in/yukitanaka",
    github: "https://github.com/ytanaka",
    summary:
      "Senior software engineer with extensive experience in building enterprise applications. Expert in Java, Spring, and cloud architecture. Strong leadership skills with experience mentoring junior developers.",
    skills: [
      "Java",
      "Spring Boot",
      "Microservices",
      "AWS",
      "PostgreSQL",
      "Docker",
      "Kubernetes",
      "React",
      "System Design",
      "Leadership",
    ],
    skillMatch: 94,
    resumeUrl: "https://example.com/resume/yuki-tanaka.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/ytanaka/enterprise-platform",
    submissionFiles: [
      { name: "architecture-documentation.pdf", url: "#", type: "application/pdf", size: "4.2 MB" },
      { name: "code-review-guidelines.pdf", url: "#", type: "application/pdf", size: "890 KB" },
      { name: "performance-analysis.pdf", url: "#", type: "application/pdf", size: "1.3 MB" },
    ],
    submissionLinks: ["https://enterprise-demo.ytanaka.dev", "https://docs.ytanaka.dev"],
    takeHomeChallengeNotes: "Exceptional enterprise-grade solution with excellent architecture and documentation.",
    codeReviewPoints: [
      "Outstanding system architecture with scalability in mind",
      "Excellent code quality with comprehensive documentation",
      "High test coverage (94%) with thorough integration tests",
      "Proper microservices design with clear boundaries",
      "Strong security implementation throughout",
      "Efficient database design and query optimization",
      "Well-implemented CI/CD pipeline",
      "Excellent monitoring and logging setup",
      "Clean code following best practices and design patterns",
      "Bonus: Comprehensive technical documentation for team onboarding",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/yuki-tanaka.mp4",
    aiGeneratedInsights: [
      "Exceptional technical leadership and expertise",
      "Strong system design and architecture skills",
      "Excellent mentoring and communication abilities",
      "Great cultural fit with focus on quality and collaboration",
      "Perfect for senior or lead engineer role",
    ],
  },
  {
    id: "cand-12",
    name: "Omar Ibrahim",
    avatar: "/professional-middle-eastern-man-software-engineer.jpg",
    title: "Data Engineer",
    location: "Pasig, Philippines",
    experience: "4 years",
    email: "omar.ibrahim@email.com",
    phone: "+63 917 234 5678",
    linkedin: "https://linkedin.com/in/omaribrahim",
    github: "https://github.com/oibrahim",
    summary:
      "Data engineer specializing in building data pipelines and analytics platforms. Experienced with Python, SQL, and big data technologies. Passionate about turning data into actionable insights.",
    skills: [
      "Python",
      "SQL",
      "Apache Spark",
      "Airflow",
      "PostgreSQL",
      "AWS",
      "ETL",
      "Data Modeling",
      "BigQuery",
      "Pandas",
    ],
    skillMatch: 81,
    resumeUrl: "https://example.com/resume/omar-ibrahim.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/oibrahim/data-pipeline",
    submissionFiles: [
      { name: "data-architecture.pdf", url: "#", type: "application/pdf", size: "2.1 MB" },
      { name: "pipeline-documentation.md", url: "#", type: "text/markdown", size: "45 KB" },
    ],
    submissionLinks: ["https://dashboard.oibrahim.dev"],
    takeHomeChallengeNotes: "Solid data engineering solution with efficient pipelines and good documentation.",
    codeReviewPoints: [
      "Well-designed data pipeline architecture",
      "Efficient ETL processes with proper error handling",
      "Good data modeling and schema design",
      "Proper use of Airflow for orchestration",
      "Clean Python code with good practices",
      "Adequate test coverage for data transformations",
      "Clear documentation of data flows",
      "Could improve: More advanced optimization techniques",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/omar-ibrahim.mp4",
    aiGeneratedInsights: [
      "Strong data engineering fundamentals",
      "Good understanding of data architecture",
      "Analytical mindset with attention to detail",
      "Eager to learn advanced big data technologies",
    ],
  },
  {
    id: "cand-13",
    name: "Sophie Laurent",
    avatar: "/professional-french-woman-developer.jpg",
    title: "UI/UX Engineer",
    location: "Taguig, Philippines",
    experience: "5 years",
    email: "sophie.laurent@email.com",
    phone: "+63 917 345 6789",
    linkedin: "https://linkedin.com/in/sophielaur ent",
    github: "https://github.com/slaurent",
    portfolio: "https://sophielaurent.design",
    summary:
      "UI/UX engineer with a perfect blend of design and development skills. Specialized in creating intuitive, beautiful interfaces with React and modern design tools. Strong advocate for user-centered design.",
    skills: [
      "React",
      "TypeScript",
      "Figma",
      "UI/UX Design",
      "TailwindCSS",
      "Framer Motion",
      "Accessibility",
      "Design Systems",
      "Prototyping",
      "User Research",
    ],
    skillMatch: 77,
    resumeUrl: "https://example.com/resume/sophie-laurent.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/slaurent/design-system",
    submissionFiles: [
      { name: "design-system.fig", url: "#", type: "application/figma", size: "5.4 MB" },
      { name: "user-research.pdf", url: "#", type: "application/pdf", size: "1.9 MB" },
      { name: "usability-testing.pdf", url: "#", type: "application/pdf", size: "1.2 MB" },
    ],
    submissionLinks: ["https://demo.sophielaurent.design", "https://storybook.sophielaurent.design"],
    takeHomeChallengeNotes: "Exceptional UI/UX work with beautiful design and excellent user experience.",
    codeReviewPoints: [
      "Outstanding design system with comprehensive components",
      "Beautiful UI with excellent attention to detail",
      "Strong accessibility implementation",
      "Smooth animations and micro-interactions",
      "Well-documented components and design guidelines",
      "Good React component architecture",
      "Responsive design across all breakpoints",
      "Could improve: More backend integration experience",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/sophie-laurent.mp4",
    aiGeneratedInsights: [
      "Exceptional UI/UX design and development skills",
      "Strong user-centered design approach",
      "Excellent communication of design decisions",
      "Would benefit from more full-stack experience",
    ],
  },
  {
    id: "cand-14",
    name: "Raj Patel",
    avatar: "/professional-indian-man-software-engineer.jpg",
    title: "Backend Developer",
    location: "Manila, Philippines",
    experience: "6 years",
    email: "raj.patel@email.com",
    phone: "+63 917 456 7890",
    linkedin: "https://linkedin.com/in/rajpatel",
    github: "https://github.com/rpatel",
    summary:
      "Backend developer with strong expertise in Python and Django. Experienced in building RESTful APIs and working with databases. Focused on writing clean, maintainable code with comprehensive tests.",
    skills: ["Python", "Django", "PostgreSQL", "Redis", "REST APIs", "Docker", "AWS", "Celery", "pytest", "Git"],
    skillMatch: 83,
    resumeUrl: "https://example.com/resume/raj-patel.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/rpatel/api-backend",
    submissionFiles: [
      { name: "api-documentation.pdf", url: "#", type: "application/pdf", size: "1.6 MB" },
      { name: "database-schema.pdf", url: "#", type: "application/pdf", size: "890 KB" },
    ],
    submissionLinks: ["https://api.rpatel.dev/docs"],
    takeHomeChallengeNotes: "Strong backend implementation with clean code and good test coverage.",
    codeReviewPoints: [
      "Well-structured Django application with clean architecture",
      "Efficient API design with proper REST conventions",
      "Good database design and query optimization",
      "High test coverage (85%) with comprehensive unit tests",
      "Proper error handling and validation",
      "Good use of caching with Redis",
      "Clear API documentation",
      "Could improve: More advanced scalability patterns",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/raj-patel.mp4",
    aiGeneratedInsights: [
      "Strong backend development skills with Python",
      "Good understanding of API design principles",
      "Methodical approach to testing and quality",
      "Solid team player with good communication",
    ],
  },
  {
    id: "cand-15",
    name: "Anna Kowalski",
    avatar: "/professional-polish-woman-developer.jpg",
    title: "Full-Stack Developer",
    location: "Cebu City, Philippines",
    experience: "4 years",
    email: "anna.kowalski@email.com",
    phone: "+63 917 567 8901",
    linkedin: "https://linkedin.com/in/annakowalski",
    github: "https://github.com/akowalski",
    summary:
      "Full-stack developer with a passion for building user-friendly web applications. Experienced with React, Node.js, and modern web technologies. Strong focus on code quality and best practices.",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "PostgreSQL",
      "Express",
      "Next.js",
      "TailwindCSS",
      "Jest",
      "Git",
      "Agile",
    ],
    skillMatch: 80,
    resumeUrl: "https://example.com/resume/anna-kowalski.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/akowalski/web-app",
    submissionFiles: [
      { name: "project-documentation.pdf", url: "#", type: "application/pdf", size: "1.3 MB" },
      { name: "test-coverage.html", url: "#", type: "text/html", size: "145 KB" },
    ],
    submissionLinks: ["https://demo.akowalski.dev"],
    takeHomeChallengeNotes: "Good full-stack implementation with clean code and solid fundamentals.",
    codeReviewPoints: [
      "Clean, well-organized codebase",
      "Good React component structure",
      "Solid backend API implementation",
      "Good test coverage (76%) for key features",
      "Proper error handling throughout",
      "Responsive UI with good user experience",
      "Clear code documentation",
      "Could improve: More advanced optimization techniques",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/anna-kowalski.mp4",
    aiGeneratedInsights: [
      "Solid full-stack development skills",
      "Good understanding of web development best practices",
      "Strong work ethic and attention to detail",
      "Team player with good collaboration skills",
    ],
  },
  {
    id: "cand-16",
    name: "Marcus Johnson",
    avatar: "/professional-african-american-man-developer.jpg",
    title: "Cloud Architect",
    location: "Bonifacio Global City, Philippines",
    experience: "9 years",
    email: "marcus.johnson@email.com",
    phone: "+63 917 678 9012",
    linkedin: "https://linkedin.com/in/marcusjohnson",
    github: "https://github.com/mjohnson",
    summary:
      "Cloud architect with extensive experience designing and implementing cloud infrastructure. Expert in AWS, Azure, and multi-cloud strategies. Strong focus on security, scalability, and cost optimization.",
    skills: [
      "AWS",
      "Azure",
      "Terraform",
      "Kubernetes",
      "Docker",
      "Python",
      "CloudFormation",
      "Security",
      "Cost Optimization",
      "Architecture",
    ],
    skillMatch: 92,
    resumeUrl: "https://example.com/resume/marcus-johnson.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/mjohnson/cloud-infrastructure",
    submissionFiles: [
      { name: "cloud-architecture.pdf", url: "#", type: "application/pdf", size: "3.8 MB" },
      { name: "security-assessment.pdf", url: "#", type: "application/pdf", size: "2.1 MB" },
      { name: "cost-analysis.xlsx", url: "#", type: "application/vnd.ms-excel", size: "456 KB" },
    ],
    submissionLinks: ["https://infrastructure.mjohnson.dev"],
    takeHomeChallengeNotes: "Exceptional cloud architecture with excellent security and cost optimization.",
    codeReviewPoints: [
      "Outstanding cloud architecture design",
      "Comprehensive security implementation",
      "Excellent infrastructure as code with Terraform",
      "Well-designed multi-region setup for high availability",
      "Cost-optimized infrastructure with proper resource sizing",
      "Comprehensive monitoring and alerting",
      "Excellent documentation and runbooks",
      "Proper disaster recovery and backup strategies",
      "Clean, maintainable infrastructure code",
      "Bonus: Implemented automated cost optimization recommendations",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/marcus-johnson.mp4",
    aiGeneratedInsights: [
      "Exceptional cloud architecture expertise",
      "Strong leadership and strategic thinking",
      "Excellent understanding of security and compliance",
      "Great communication of technical concepts to stakeholders",
      "Perfect for senior architect or principal engineer role",
    ],
  },
  {
    id: "cand-17",
    name: "Mei Lin",
    avatar: "/professional-chinese-woman-developer.jpg",
    title: "Frontend Developer",
    location: "Makati, Philippines",
    experience: "3 years",
    email: "mei.lin@email.com",
    phone: "+63 917 789 0123",
    linkedin: "https://linkedin.com/in/meilin",
    github: "https://github.com/mlin",
    portfolio: "https://meilin.dev",
    summary:
      "Frontend developer passionate about creating responsive, accessible web applications. Skilled in React, Vue, and modern CSS frameworks. Eager to learn and grow in a collaborative environment.",
    skills: [
      "React",
      "Vue.js",
      "JavaScript",
      "TypeScript",
      "CSS",
      "TailwindCSS",
      "HTML",
      "Responsive Design",
      "Git",
      "Webpack",
    ],
    skillMatch: 74,
    resumeUrl: "https://example.com/resume/mei-lin.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/mlin/portfolio-project",
    submissionFiles: [
      { name: "design-mockups.pdf", url: "#", type: "application/pdf", size: "1.8 MB" },
      { name: "component-documentation.md", url: "#", type: "text/markdown", size: "28 KB" },
    ],
    submissionLinks: ["https://demo.meilin.dev"],
    takeHomeChallengeNotes: "Good frontend implementation with clean code and responsive design.",
    codeReviewPoints: [
      "Clean React component structure",
      "Good responsive design implementation",
      "Proper use of modern CSS techniques",
      "Functional components with hooks",
      "Basic test coverage for key components",
      "Good attention to browser compatibility",
      "Could improve: More advanced state management",
      "Could improve: Accessibility features",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/mei-lin.mp4",
    aiGeneratedInsights: [
      "Solid frontend development fundamentals",
      "Eager to learn and improve skills",
      "Good attitude and team collaboration",
      "Would benefit from mentorship in advanced topics",
    ],
  },
  {
    id: "cand-18",
    name: "Diego Fernandez",
    avatar: "/professional-latino-man-software-engineer.jpg",
    title: "Security Engineer",
    location: "Quezon City, Philippines",
    experience: "7 years",
    email: "diego.fernandez@email.com",
    phone: "+63 917 890 1234",
    linkedin: "https://linkedin.com/in/diegofernandez",
    github: "https://github.com/dfernandez",
    summary:
      "Security engineer specializing in application security and penetration testing. Experienced in identifying and mitigating security vulnerabilities. Strong knowledge of secure coding practices and compliance standards.",
    skills: [
      "Security",
      "Penetration Testing",
      "OWASP",
      "Python",
      "Burp Suite",
      "Metasploit",
      "AWS Security",
      "Compliance",
      "Threat Modeling",
      "Incident Response",
    ],
    skillMatch: 89,
    resumeUrl: "https://example.com/resume/diego-fernandez.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/dfernandez/security-audit",
    submissionFiles: [
      { name: "security-assessment.pdf", url: "#", type: "application/pdf", size: "2.9 MB" },
      { name: "vulnerability-report.pdf", url: "#", type: "application/pdf", size: "1.7 MB" },
      { name: "remediation-plan.pdf", url: "#", type: "application/pdf", size: "1.1 MB" },
    ],
    submissionLinks: ["https://security-dashboard.dfernandez.dev"],
    takeHomeChallengeNotes: "Comprehensive security assessment with detailed findings and recommendations.",
    codeReviewPoints: [
      "Thorough security analysis with detailed findings",
      "Excellent identification of vulnerabilities",
      "Comprehensive remediation recommendations",
      "Good understanding of OWASP Top 10",
      "Proper threat modeling approach",
      "Clear documentation of security issues",
      "Practical solutions with code examples",
      "Good knowledge of secure coding practices",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/diego-fernandez.mp4",
    aiGeneratedInsights: [
      "Strong security expertise and knowledge",
      "Excellent analytical and problem-solving skills",
      "Good communication of security concepts",
      "Proactive approach to security best practices",
    ],
  },
  {
    id: "cand-19",
    name: "Fatima Al-Rashid",
    avatar: "/professional-middle-eastern-woman-developer.jpg",
    title: "Machine Learning Engineer",
    location: "Pasig, Philippines",
    experience: "5 years",
    email: "fatima.alrashid@email.com",
    phone: "+63 917 901 2345",
    linkedin: "https://linkedin.com/in/fatimaalrashid",
    github: "https://github.com/falrashid",
    summary:
      "Machine learning engineer with expertise in building and deploying ML models. Experienced with Python, TensorFlow, and cloud ML platforms. Passionate about applying AI to solve real-world problems.",
    skills: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Machine Learning",
      "Deep Learning",
      "NLP",
      "AWS SageMaker",
      "Data Science",
      "Pandas",
      "Scikit-learn",
    ],
    skillMatch: 85,
    resumeUrl: "https://example.com/resume/fatima-alrashid.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/falrashid/ml-model",
    submissionFiles: [
      { name: "model-documentation.pdf", url: "#", type: "application/pdf", size: "2.3 MB" },
      { name: "training-results.pdf", url: "#", type: "application/pdf", size: "1.4 MB" },
      { name: "model-evaluation.ipynb", url: "#", type: "application/x-ipynb+json", size: "567 KB" },
    ],
    submissionLinks: ["https://ml-demo.falrashid.dev", "https://colab.research.google.com/notebook"],
    takeHomeChallengeNotes: "Excellent ML implementation with well-documented model and good performance.",
    codeReviewPoints: [
      "Well-designed ML pipeline with proper data preprocessing",
      "Good model architecture with appropriate hyperparameters",
      "Comprehensive model evaluation with multiple metrics",
      "Clean, well-documented code",
      "Proper handling of data imbalance",
      "Good feature engineering approach",
      "Efficient model deployment strategy",
      "Could improve: More extensive hyperparameter tuning",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/fatima-alrashid.mp4",
    aiGeneratedInsights: [
      "Strong machine learning and data science skills",
      "Good understanding of ML best practices",
      "Excellent problem-solving approach",
      "Passionate about AI and continuous learning",
    ],
  },
  {
    id: "cand-20",
    name: "Thomas O'Brien",
    avatar: "/professional-irish-man-developer.jpg",
    title: "Full-Stack Developer",
    location: "Taguig, Philippines",
    experience: "6 years",
    email: "thomas.obrien@email.com",
    phone: "+63 917 012 3456",
    linkedin: "https://linkedin.com/in/thomasobrien",
    github: "https://github.com/tobrien",
    summary:
      "Experienced full-stack developer with a track record of delivering high-quality web applications. Proficient in React, Node.js, and cloud technologies. Strong communicator with excellent problem-solving skills.",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "PostgreSQL",
      "AWS",
      "Docker",
      "GraphQL",
      "Next.js",
      "TailwindCSS",
      "CI/CD",
    ],
    skillMatch: 90,
    resumeUrl: "https://example.com/resume/thomas-obrien.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/tobrien/saas-platform",
    submissionFiles: [
      { name: "technical-documentation.pdf", url: "#", type: "application/pdf", size: "2.6 MB" },
      { name: "deployment-guide.pdf", url: "#", type: "application/pdf", size: "1.2 MB" },
      { name: "test-results.html", url: "#", type: "text/html", size: "178 KB" },
    ],
    submissionLinks: ["https://saas-demo.tobrien.dev", "https://api.tobrien.dev/graphql"],
    takeHomeChallengeNotes: "Excellent full-stack implementation with production-ready code quality.",
    codeReviewPoints: [
      "Excellent full-stack architecture with clean separation",
      "High-quality React components with proper patterns",
      "Well-designed GraphQL API with efficient resolvers",
      "High test coverage (88%) across frontend and backend",
      "Proper error handling and validation throughout",
      "Good performance optimization techniques",
      "Clean, maintainable codebase with consistent patterns",
      "Comprehensive documentation",
      "Proper CI/CD setup with automated testing",
      "Bonus: Implemented real-time features with WebSockets",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/thomas-obrien.mp4",
    aiGeneratedInsights: [
      "Excellent full-stack development skills",
      "Strong technical leadership potential",
      "Great communication and collaboration skills",
      "Proven track record of delivering quality work",
      "Great cultural fit with team-oriented mindset",
    ],
  },
]

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

export function getRandomizedCandidates(): CandidateProfile[] {
  return shuffleArray(mockCandidates)
}
