import type { CandidateProfile } from "@/types/workspace"

export const mockCandidates: CandidateProfile[] = [
  {
    id: "cand-1",
    name: "Sarah Chen",
    avatar: "/professional-headshot-asian-woman-software-develop.jpg",
    title: "Senior Full-Stack Developer",
    location: "Manila, Philippines",
    experience: "6 years",
    email: "sarah.chen@email.com",
    phone: "+63 917 123 4567",
    linkedin: "https://linkedin.com/in/sarahchen",
    github: "https://github.com/sarahchen",
    portfolio: "https://sarahchen.dev",
    summary:
      "Passionate full-stack developer with 6 years of experience building scalable web applications. Specialized in React, Node.js, and cloud architecture. Led multiple teams to deliver high-impact projects on time and under budget. Strong advocate for clean code and test-driven development.",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "AWS",
      "PostgreSQL",
      "Docker",
      "Kubernetes",
      "GraphQL",
      "Next.js",
      "TailwindCSS",
    ],
    skillMatch: 95,
    resumeUrl: "https://example.com/resume/sarah-chen.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/sarahchen/ecommerce-platform",
    submissionFiles: [
      { name: "project-documentation.pdf", url: "#", type: "application/pdf", size: "2.4 MB" },
      { name: "architecture-diagram.png", url: "#", type: "image/png", size: "856 KB" },
      { name: "test-coverage-report.html", url: "#", type: "text/html", size: "124 KB" },
    ],
    submissionLinks: ["https://demo.sarahchen-challenge.vercel.app", "https://www.loom.com/share/demo-walkthrough"],
    takeHomeChallengeNotes:
      "Excellent code quality with comprehensive tests. Implemented all required features plus bonus optimizations. Clean architecture and well-documented code.",
    codeReviewPoints: [
      "Excellent component architecture with clear separation of concerns",
      "Comprehensive test coverage (95%) including unit, integration, and e2e tests",
      "Implemented all required features plus performance optimizations",
      "Clean, readable code with consistent naming conventions",
      "Proper error handling and edge case management",
      "Well-documented API endpoints with OpenAPI/Swagger specs",
      "Efficient database queries with proper indexing",
      "Security best practices: input validation, SQL injection prevention, XSS protection",
      "Responsive design that works seamlessly across all devices",
      "Bonus: Added caching layer that improved response times by 40%",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/sarah-chen.mp4",
    aiInterviewTranscript:
      "Q: Tell me about your experience with microservices.\nA: I've architected and deployed multiple microservices systems using Node.js and Docker. In my last role, I led the migration from a monolith to microservices, which improved our deployment frequency by 300%...",
    aiGeneratedInsights: [
      "Strong technical skills with proven track record in full-stack development",
      "Excellent problem-solving abilities demonstrated in coding challenge",
      "Great communication skills and team leadership experience",
      "Proactive learner who stays current with latest technologies",
      "Cultural fit: Values collaboration and continuous improvement",
    ],
  },
  {
    id: "cand-2",
    name: "Michael Rodriguez",
    avatar: "/professional-headshot-hispanic-man-software-engine.jpg",
    title: "Full-Stack Engineer",
    location: "Quezon City, Philippines",
    experience: "4 years",
    email: "michael.rodriguez@email.com",
    phone: "+63 917 234 5678",
    linkedin: "https://linkedin.com/in/michaelrodriguez",
    github: "https://github.com/mrodriguez",
    summary:
      "Enthusiastic full-stack engineer with a strong foundation in modern web technologies. Experienced in building responsive applications with React and Node.js. Quick learner with a passion for solving complex problems and delivering user-friendly solutions.",
    skills: ["React", "Node.js", "JavaScript", "MongoDB", "Express", "REST APIs", "Git", "Agile", "CSS", "HTML"],
    skillMatch: 87,
    resumeUrl: "https://example.com/resume/michael-rodriguez.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/mrodriguez/task-manager-app",
    submissionFiles: [
      { name: "README.md", url: "#", type: "text/markdown", size: "12 KB" },
      { name: "setup-instructions.pdf", url: "#", type: "application/pdf", size: "456 KB" },
    ],
    submissionLinks: ["https://task-manager-demo.netlify.app"],
    takeHomeChallengeNotes: "Good implementation with solid fundamentals. Code is clean and functional.",
    codeReviewPoints: [
      "Solid implementation of core features with good code organization",
      "Functional components with proper React hooks usage",
      "Good test coverage (75%) for critical paths",
      "RESTful API design follows standard conventions",
      "Basic error handling implemented for common scenarios",
      "Responsive layout works well on mobile and desktop",
      "Code is readable with helpful comments where needed",
      "Could improve: More comprehensive input validation",
      "Could improve: Additional edge case handling in async operations",
      "Overall: Strong fundamentals with room for optimization",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/michael-rodriguez.mp4",
    aiGeneratedInsights: [
      "Solid technical foundation with good understanding of web development",
      "Eager to learn and grow in the role",
      "Good communication skills and positive attitude",
      "Shows potential for rapid skill development",
    ],
  },
  {
    id: "cand-3",
    name: "Priya Sharma",
    avatar: "/professional-headshot-indian-woman-software-engine.jpg",
    title: "Software Engineer",
    location: "Makati, Philippines",
    experience: "5 years",
    email: "priya.sharma@email.com",
    phone: "+63 917 345 6789",
    linkedin: "https://linkedin.com/in/priyasharma",
    github: "https://github.com/psharma",
    summary:
      "Detail-oriented software engineer with expertise in backend development and database optimization. Strong problem-solving skills and experience with distributed systems. Committed to writing efficient, maintainable code.",
    skills: ["Python", "Django", "PostgreSQL", "Redis", "Docker", "AWS", "REST APIs", "GraphQL", "React", "TypeScript"],
    skillMatch: 82,
    resumeUrl: "https://example.com/resume/priya-sharma.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/psharma/api-service",
    submissionFiles: [
      { name: "api-documentation.pdf", url: "#", type: "application/pdf", size: "1.8 MB" },
      { name: "postman-collection.json", url: "#", type: "application/json", size: "45 KB" },
    ],
    submissionLinks: ["https://api-demo.psharma.dev/docs"],
    takeHomeChallengeNotes: "Strong backend implementation with excellent database design.",
    codeReviewPoints: [
      "Excellent database schema design with proper normalization",
      "Efficient API endpoints with good performance characteristics",
      "Comprehensive error handling and logging",
      "Good test coverage for backend logic (82%)",
      "Well-structured code with clear separation of concerns",
      "Proper use of caching strategies for frequently accessed data",
      "Security: Implemented authentication and authorization correctly",
      "Could improve: Frontend UI could be more polished",
      "Could improve: Additional client-side validation",
      "Overall: Strong backend skills, frontend needs development",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/priya-sharma.mp4",
    aiGeneratedInsights: [
      "Exceptional backend development skills",
      "Strong understanding of system architecture and scalability",
      "Methodical approach to problem-solving",
      "Would benefit from more frontend experience",
    ],
  },
  {
    id: "cand-4",
    name: "James Wilson",
    avatar: "/professional-headshot-caucasian-man-frontend-devel.jpg",
    title: "Frontend Developer",
    location: "Taguig, Philippines",
    experience: "3 years",
    email: "james.wilson@email.com",
    phone: "+63 917 456 7890",
    linkedin: "https://linkedin.com/in/jameswilson",
    github: "https://github.com/jwilson",
    portfolio: "https://jameswilson.design",
    summary:
      "Creative frontend developer with a keen eye for design and user experience. Specialized in building beautiful, accessible interfaces with React and modern CSS. Passionate about creating delightful user experiences.",
    skills: [
      "React",
      "TypeScript",
      "CSS",
      "TailwindCSS",
      "Figma",
      "Next.js",
      "Framer Motion",
      "Accessibility",
      "UI/UX",
    ],
    skillMatch: 75,
    resumeUrl: "https://example.com/resume/james-wilson.pdf",
    takeHomeChallengeStatus: "completed",
    submissionFiles: [
      { name: "design-mockups.fig", url: "#", type: "application/figma", size: "3.2 MB" },
      { name: "component-library.pdf", url: "#", type: "application/pdf", size: "1.1 MB" },
    ],
    submissionLinks: ["https://jwilson-challenge.vercel.app", "https://www.figma.com/file/design-system"],
    takeHomeChallengeNotes: "Beautiful UI with excellent attention to detail and accessibility.",
    codeReviewPoints: [
      "Outstanding UI/UX design with pixel-perfect implementation",
      "Excellent accessibility features (WCAG 2.1 AA compliant)",
      "Smooth animations and transitions using Framer Motion",
      "Responsive design that adapts beautifully to all screen sizes",
      "Clean, maintainable CSS with good use of Tailwind utilities",
      "Well-structured React components with proper prop types",
      "Good attention to performance (lazy loading, code splitting)",
      "Could improve: Backend integration could be more robust",
      "Could improve: More comprehensive error handling",
      "Overall: Exceptional frontend skills, needs backend development",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/james-wilson.mp4",
    aiGeneratedInsights: [
      "Exceptional design and frontend development skills",
      "Strong focus on user experience and accessibility",
      "Creative problem solver with attention to detail",
      "Would benefit from more backend experience",
    ],
  },
  {
    id: "cand-5",
    name: "Elena Popescu",
    avatar: "/professional-headshot-european-woman-developer-exp.jpg",
    title: "Full-Stack Developer",
    location: "Pasig, Philippines",
    experience: "7 years",
    email: "elena.popescu@email.com",
    phone: "+63 917 567 8901",
    linkedin: "https://linkedin.com/in/elenapopescu",
    github: "https://github.com/epopescu",
    summary:
      "Experienced full-stack developer with a strong background in e-commerce and fintech applications. Expert in building secure, scalable systems with modern technologies. Proven track record of delivering complex projects.",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "PostgreSQL",
      "Redis",
      "AWS",
      "Stripe",
      "Security",
      "Microservices",
      "Docker",
    ],
    skillMatch: 91,
    resumeUrl: "https://example.com/resume/elena-popescu.pdf",
    takeHomeChallengeStatus: "completed",
    githubRepo: "https://github.com/epopescu/payment-system",
    submissionFiles: [
      { name: "technical-writeup.pdf", url: "#", type: "application/pdf", size: "2.1 MB" },
      { name: "security-audit.pdf", url: "#", type: "application/pdf", size: "890 KB" },
      { name: "performance-metrics.xlsx", url: "#", type: "application/vnd.ms-excel", size: "234 KB" },
    ],
    submissionLinks: ["https://payment-demo.epopescu.dev", "https://docs.epopescu.dev/api-reference"],
    takeHomeChallengeNotes: "Exceptional work with strong focus on security and scalability.",
    codeReviewPoints: [
      "Excellent system architecture with microservices design",
      "Comprehensive security implementation (encryption, authentication, authorization)",
      "High test coverage (92%) with thorough integration tests",
      "Efficient database design with proper indexing and query optimization",
      "Well-documented code and API endpoints",
      "Proper error handling and logging throughout the application",
      "Performance optimizations: caching, lazy loading, code splitting",
      "Scalable infrastructure setup with Docker and AWS",
      "Clean code with consistent patterns and best practices",
      "Bonus: Implemented CI/CD pipeline with automated testing and deployment",
    ],
    aiInterviewStatus: "completed",
    aiInterviewRecordingUrl: "https://example.com/interviews/elena-popescu.mp4",
    aiGeneratedInsights: [
      "Highly experienced with strong technical leadership",
      "Excellent understanding of security and scalability",
      "Proven track record in complex system development",
      "Strong communication and documentation skills",
      "Great cultural fit with focus on quality and best practices",
    ],
  },
]

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

export function getRandomizedCandidates(): CandidateProfile[] {
  return shuffleArray(mockCandidates)
}
